// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module lwe_encrypt_encrypt_one_lwe (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        context_Addr_A,
        context_EN_A,
        context_WEN_A,
        context_Din_A,
        context_Dout_A,
        input_pkt_data,
        data_out_TDATA,
        data_out_TVALID,
        data_out_TREADY,
        data_out_TKEEP,
        data_out_TSTRB,
        data_out_TUSER,
        data_out_TLAST,
        data_out_TID,
        data_out_TDEST,
        mask_dimension,
        input_mode,
        noise_mode,
        noise_bound_log2,
        delta,
        base_seed,
        nonce,
        request_index
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] context_Addr_A;
output   context_EN_A;
output  [63:0] context_WEN_A;
output  [511:0] context_Din_A;
input  [511:0] context_Dout_A;
input  [127:0] input_pkt_data;
output  [511:0] data_out_TDATA;
output   data_out_TVALID;
input   data_out_TREADY;
output  [63:0] data_out_TKEEP;
output  [63:0] data_out_TSTRB;
output  [7:0] data_out_TUSER;
output  [0:0] data_out_TLAST;
output  [7:0] data_out_TID;
output  [7:0] data_out_TDEST;
input  [31:0] mask_dimension;
input  [31:0] input_mode;
input  [31:0] noise_mode;
input  [31:0] noise_bound_log2;
input  [63:0] delta;
input  [63:0] base_seed;
input  [63:0] nonce;
input  [31:0] request_index;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln870_fu_152_p2;
reg   [0:0] icmp_ln870_reg_184;
wire    ap_CS_fsm_state2;
wire  signed [63:0] input_word_V_fu_158_p1;
reg  signed [63:0] input_word_V_reg_194;
reg   [63:0] input_noise_V_reg_200;
wire   [63:0] grp_fu_172_p2;
reg   [63:0] mul_ln208_reg_205;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire   [63:0] encoded_fu_178_p3;
reg   [63:0] encoded_reg_240;
wire    grp_encrypt_encoded_lwe_fu_118_ap_start;
wire    grp_encrypt_encoded_lwe_fu_118_ap_done;
wire    grp_encrypt_encoded_lwe_fu_118_ap_idle;
wire    grp_encrypt_encoded_lwe_fu_118_ap_ready;
wire   [31:0] grp_encrypt_encoded_lwe_fu_118_context_Addr_A;
wire    grp_encrypt_encoded_lwe_fu_118_context_EN_A;
wire   [63:0] grp_encrypt_encoded_lwe_fu_118_context_WEN_A;
wire   [511:0] grp_encrypt_encoded_lwe_fu_118_context_Din_A;
wire   [511:0] grp_encrypt_encoded_lwe_fu_118_data_out_TDATA;
wire    grp_encrypt_encoded_lwe_fu_118_data_out_TVALID;
wire    grp_encrypt_encoded_lwe_fu_118_data_out_TREADY;
wire   [63:0] grp_encrypt_encoded_lwe_fu_118_data_out_TKEEP;
wire   [63:0] grp_encrypt_encoded_lwe_fu_118_data_out_TSTRB;
wire   [7:0] grp_encrypt_encoded_lwe_fu_118_data_out_TUSER;
wire   [0:0] grp_encrypt_encoded_lwe_fu_118_data_out_TLAST;
wire   [7:0] grp_encrypt_encoded_lwe_fu_118_data_out_TID;
wire   [7:0] grp_encrypt_encoded_lwe_fu_118_data_out_TDEST;
reg    grp_encrypt_encoded_lwe_fu_118_ap_start_reg;
wire    ap_CS_fsm_state8;
wire  signed [63:0] grp_fu_172_p0;
reg   [7:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 icmp_ln870_reg_184 = 1'd0;
#0 input_word_V_reg_194 = 64'd0;
#0 input_noise_V_reg_200 = 64'd0;
#0 mul_ln208_reg_205 = 64'd0;
#0 encoded_reg_240 = 64'd0;
#0 grp_encrypt_encoded_lwe_fu_118_ap_start_reg = 1'b0;
end

lwe_encrypt_encrypt_encoded_lwe grp_encrypt_encoded_lwe_fu_118(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_encrypt_encoded_lwe_fu_118_ap_start),
    .ap_done(grp_encrypt_encoded_lwe_fu_118_ap_done),
    .ap_idle(grp_encrypt_encoded_lwe_fu_118_ap_idle),
    .ap_ready(grp_encrypt_encoded_lwe_fu_118_ap_ready),
    .context_Addr_A(grp_encrypt_encoded_lwe_fu_118_context_Addr_A),
    .context_EN_A(grp_encrypt_encoded_lwe_fu_118_context_EN_A),
    .context_WEN_A(grp_encrypt_encoded_lwe_fu_118_context_WEN_A),
    .context_Din_A(grp_encrypt_encoded_lwe_fu_118_context_Din_A),
    .context_Dout_A(context_Dout_A),
    .data_out_TDATA(grp_encrypt_encoded_lwe_fu_118_data_out_TDATA),
    .data_out_TVALID(grp_encrypt_encoded_lwe_fu_118_data_out_TVALID),
    .data_out_TREADY(grp_encrypt_encoded_lwe_fu_118_data_out_TREADY),
    .data_out_TKEEP(grp_encrypt_encoded_lwe_fu_118_data_out_TKEEP),
    .data_out_TSTRB(grp_encrypt_encoded_lwe_fu_118_data_out_TSTRB),
    .data_out_TUSER(grp_encrypt_encoded_lwe_fu_118_data_out_TUSER),
    .data_out_TLAST(grp_encrypt_encoded_lwe_fu_118_data_out_TLAST),
    .data_out_TID(grp_encrypt_encoded_lwe_fu_118_data_out_TID),
    .data_out_TDEST(grp_encrypt_encoded_lwe_fu_118_data_out_TDEST),
    .mask_dimension(mask_dimension),
    .noise_mode(noise_mode),
    .noise_bound_log2(noise_bound_log2),
    .encoded(encoded_reg_240),
    .input_noise(input_noise_V_reg_200),
    .base_seed(base_seed),
    .nonce(nonce),
    .ciphertext_index(request_index)
);

lwe_encrypt_mul_64s_64s_64_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
mul_64s_64s_64_5_1_U44(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_172_p0),
    .din1(delta),
    .ce(1'b1),
    .dout(grp_fu_172_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        encoded_reg_240 <= 64'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            encoded_reg_240 <= encoded_fu_178_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_encrypt_encoded_lwe_fu_118_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_encrypt_encoded_lwe_fu_118_ap_start_reg <= 1'b1;
        end else if ((grp_encrypt_encoded_lwe_fu_118_ap_ready == 1'b1)) begin
            grp_encrypt_encoded_lwe_fu_118_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln870_reg_184 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            icmp_ln870_reg_184 <= icmp_ln870_fu_152_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        input_noise_V_reg_200 <= 64'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            input_noise_V_reg_200 <= {{input_pkt_data[127:64]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        input_word_V_reg_194 <= 64'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            input_word_V_reg_194 <= input_word_V_fu_158_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        mul_ln208_reg_205 <= 64'd0;
    end else begin
        if (((icmp_ln870_reg_184 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
            mul_ln208_reg_205 <= grp_fu_172_p2;
        end
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((grp_encrypt_encoded_lwe_fu_118_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_encrypt_encoded_lwe_fu_118_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_encrypt_encoded_lwe_fu_118_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign context_Addr_A = grp_encrypt_encoded_lwe_fu_118_context_Addr_A;

assign context_Din_A = 512'd0;

assign context_EN_A = grp_encrypt_encoded_lwe_fu_118_context_EN_A;

assign context_WEN_A = 64'd0;

assign data_out_TDATA = grp_encrypt_encoded_lwe_fu_118_data_out_TDATA;

assign data_out_TDEST = grp_encrypt_encoded_lwe_fu_118_data_out_TDEST;

assign data_out_TID = grp_encrypt_encoded_lwe_fu_118_data_out_TID;

assign data_out_TKEEP = grp_encrypt_encoded_lwe_fu_118_data_out_TKEEP;

assign data_out_TLAST = grp_encrypt_encoded_lwe_fu_118_data_out_TLAST;

assign data_out_TSTRB = grp_encrypt_encoded_lwe_fu_118_data_out_TSTRB;

assign data_out_TUSER = grp_encrypt_encoded_lwe_fu_118_data_out_TUSER;

assign data_out_TVALID = grp_encrypt_encoded_lwe_fu_118_data_out_TVALID;

assign encoded_fu_178_p3 = ((icmp_ln870_reg_184[0:0] == 1'b1) ? mul_ln208_reg_205 : input_word_V_reg_194);

assign grp_encrypt_encoded_lwe_fu_118_ap_start = grp_encrypt_encoded_lwe_fu_118_ap_start_reg;

assign grp_encrypt_encoded_lwe_fu_118_data_out_TREADY = (data_out_TREADY & ap_CS_fsm_state8);

assign grp_fu_172_p0 = input_pkt_data[63:0];

assign icmp_ln870_fu_152_p2 = ((input_mode == 32'd1) ? 1'b1 : 1'b0);

assign input_word_V_fu_158_p1 = input_pkt_data[63:0];

endmodule //lwe_encrypt_encrypt_one_lwe
