// ==============================================================
// Generated by Vitis HLS v2023.2.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module AssScheduler_ContextReceiver (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        acc_context_data_recv_from_datamover_TVALID,
        tdest_dout,
        tdest_empty_n,
        tdest_read,
        acc_context_data_send_to_acc_TREADY,
        context_add_lists_din,
        context_add_lists_full_n,
        context_add_lists_write,
        acc_context_data_recv_from_datamover_TDATA,
        acc_context_data_recv_from_datamover_TREADY,
        acc_context_data_recv_from_datamover_TKEEP,
        acc_context_data_recv_from_datamover_TSTRB,
        acc_context_data_recv_from_datamover_TLAST,
        acc_context_data_recv_from_datamover_TID,
        acc_context_data_recv_from_datamover_TDEST,
        acc_context_data_send_to_acc_TDATA,
        acc_context_data_send_to_acc_TVALID,
        acc_context_data_send_to_acc_TKEEP,
        acc_context_data_send_to_acc_TSTRB,
        acc_context_data_send_to_acc_TLAST,
        acc_context_data_send_to_acc_TID,
        acc_context_data_send_to_acc_TDEST,
        acc_context_data_recv_from_datamover_TDATA_blk_n,
        acc_context_data_send_to_acc_TDATA_blk_n,
        tdest_blk_n,
        context_add_lists_blk_n
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   acc_context_data_recv_from_datamover_TVALID;
input  [7:0] tdest_dout;
input   tdest_empty_n;
output   tdest_read;
input   acc_context_data_send_to_acc_TREADY;
output  [511:0] context_add_lists_din;
input   context_add_lists_full_n;
output   context_add_lists_write;
input  [511:0] acc_context_data_recv_from_datamover_TDATA;
output   acc_context_data_recv_from_datamover_TREADY;
input  [63:0] acc_context_data_recv_from_datamover_TKEEP;
input  [63:0] acc_context_data_recv_from_datamover_TSTRB;
input  [0:0] acc_context_data_recv_from_datamover_TLAST;
input  [7:0] acc_context_data_recv_from_datamover_TID;
input  [7:0] acc_context_data_recv_from_datamover_TDEST;
output  [511:0] acc_context_data_send_to_acc_TDATA;
output   acc_context_data_send_to_acc_TVALID;
output  [63:0] acc_context_data_send_to_acc_TKEEP;
output  [63:0] acc_context_data_send_to_acc_TSTRB;
output  [0:0] acc_context_data_send_to_acc_TLAST;
output  [7:0] acc_context_data_send_to_acc_TID;
output  [7:0] acc_context_data_send_to_acc_TDEST;
output   acc_context_data_recv_from_datamover_TDATA_blk_n;
output   acc_context_data_send_to_acc_TDATA_blk_n;
output   tdest_blk_n;
output   context_add_lists_blk_n;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg tdest_read;
reg context_add_lists_write;
reg acc_context_data_recv_from_datamover_TREADY;
reg acc_context_data_send_to_acc_TVALID;
reg[0:0] acc_context_data_send_to_acc_TLAST;
reg[7:0] acc_context_data_send_to_acc_TDEST;
reg acc_context_data_recv_from_datamover_TDATA_blk_n;
reg acc_context_data_send_to_acc_TDATA_blk_n;
reg tdest_blk_n;
reg context_add_lists_blk_n;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire   [0:0] grp_nbreadreq_fu_92_p8;
reg    ap_predicate_op9_read_state1;
reg    ap_predicate_op23_read_state1;
reg    ap_predicate_op35_read_state1;
reg    ap_predicate_op45_read_state1;
wire   [0:0] tmp_45_nbreadreq_fu_126_p3;
reg    ap_predicate_op62_read_state1;
reg    ap_predicate_op68_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
(*mark_debug="true"*) reg   [2:0] fsm_state_2_load_reg_316;
reg   [0:0] tmp_44_reg_320;
reg    ap_predicate_op80_write_state2;
reg   [0:0] tmp_43_reg_329;
reg    ap_predicate_op82_write_state2;
reg    ap_predicate_op83_write_state2;
reg   [0:0] tmp_s_reg_338;
reg    ap_predicate_op85_write_state2;
reg   [0:0] tmp_42_reg_347;
reg   [0:0] icmp_ln548_reg_355;
reg   [0:0] context_pkt_last_reg_351;
reg    ap_predicate_op87_write_state2;
reg    ap_predicate_op89_write_state2;
reg   [0:0] tmp_reg_359;
reg   [0:0] tmp_45_reg_363;
reg    ap_predicate_op92_write_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state2_io;
reg    ap_block_pp0_stage0_subdone;
(*mark_debug="true"*) reg   [2:0] fsm_state_2;
reg   [7:0] dest;
reg   [63:0] available_buf_num;
wire    ap_block_pp0_stage0;
reg   [511:0] reg_191;
reg    ap_block_pp0_stage0_11001;
reg   [63:0] reg_197;
reg   [63:0] reg_202;
reg   [7:0] reg_207;
wire   [0:0] context_pkt_last_4_fu_226_p2;
reg   [0:0] context_pkt_last_4_reg_324;
wire   [0:0] grp_fu_183_p1;
reg   [0:0] context_pkt_last_2_reg_333;
reg   [0:0] context_pkt_last_1_reg_342;
wire   [0:0] icmp_ln548_fu_288_p2;
reg   [0:0] context_pkt_last_5_reg_367;
reg   [7:0] context_pkt_dest_1_reg_372;
wire   [2:0] select_ln536_1_fu_240_p3;
wire   [63:0] trunc_ln521_fu_254_p1;
wire   [63:0] add_ln547_fu_276_p2;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln534_fu_220_p2;
wire   [2:0] select_ln536_fu_232_p3;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_311;
reg    ap_condition_434;
reg    ap_condition_439;
reg    ap_condition_442;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 fsm_state_2_load_reg_316 = 3'd0;
#0 tmp_44_reg_320 = 1'd0;
#0 tmp_43_reg_329 = 1'd0;
#0 tmp_s_reg_338 = 1'd0;
#0 tmp_42_reg_347 = 1'd0;
#0 icmp_ln548_reg_355 = 1'd0;
#0 context_pkt_last_reg_351 = 1'd0;
#0 tmp_reg_359 = 1'd0;
#0 tmp_45_reg_363 = 1'd0;
#0 fsm_state_2 = 3'd0;
#0 dest = 8'd0;
#0 available_buf_num = 64'd0;
#0 reg_191 = 512'd0;
#0 reg_197 = 64'd0;
#0 reg_202 = 64'd0;
#0 reg_207 = 8'd0;
#0 context_pkt_last_4_reg_324 = 1'd0;
#0 context_pkt_last_2_reg_333 = 1'd0;
#0 context_pkt_last_1_reg_342 = 1'd0;
#0 context_pkt_last_5_reg_367 = 1'd0;
#0 context_pkt_dest_1_reg_372 = 8'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        available_buf_num <= 64'd0;
    end else begin
        if ((1'b1 == ap_condition_434)) begin
            if (((fsm_state_2 == 3'd4) & (grp_fu_183_p1 == 1'd1))) begin
                available_buf_num <= add_ln547_fu_276_p2;
            end else if ((fsm_state_2 == 3'd2)) begin
                available_buf_num <= trunc_ln521_fu_254_p1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        context_pkt_dest_1_reg_372 <= 8'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            context_pkt_dest_1_reg_372 <= tdest_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        context_pkt_last_1_reg_342 <= 1'd0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            context_pkt_last_1_reg_342 <= acc_context_data_recv_from_datamover_TLAST;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        context_pkt_last_2_reg_333 <= 1'd0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            context_pkt_last_2_reg_333 <= acc_context_data_recv_from_datamover_TLAST;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        context_pkt_last_4_reg_324 <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            context_pkt_last_4_reg_324 <= context_pkt_last_4_fu_226_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        context_pkt_last_5_reg_367 <= 1'd0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            context_pkt_last_5_reg_367 <= acc_context_data_recv_from_datamover_TLAST;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        context_pkt_last_reg_351 <= 1'd0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            context_pkt_last_reg_351 <= acc_context_data_recv_from_datamover_TLAST;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        dest <= 8'd0;
    end else begin
        if ((~(fsm_state_2_load_reg_316 == 3'd3) & ~(fsm_state_2_load_reg_316 == 3'd4) & ~(fsm_state_2_load_reg_316 == 3'd1) & ~(fsm_state_2_load_reg_316 == 3'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_45_reg_363 == 1'd1) & (tmp_reg_359 == 1'd1))) begin
            dest <= context_pkt_dest_1_reg_372;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        fsm_state_2 <= 3'd0;
    end else begin
        if ((1'b1 == ap_condition_434)) begin
            if ((1'b1 == ap_condition_442)) begin
                fsm_state_2 <= 3'd1;
            end else if ((1'b1 == ap_condition_439)) begin
                fsm_state_2 <= 3'd0;
            end else if ((fsm_state_2 == 3'd1)) begin
                fsm_state_2 <= 3'd2;
            end else if ((fsm_state_2 == 3'd2)) begin
                fsm_state_2 <= 3'd3;
            end else if ((fsm_state_2 == 3'd3)) begin
                fsm_state_2 <= select_ln536_1_fu_240_p3;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        fsm_state_2_load_reg_316 <= 3'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            fsm_state_2_load_reg_316 <= fsm_state_2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln548_reg_355 <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            icmp_ln548_reg_355 <= icmp_ln548_fu_288_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        reg_191 <= 512'd0;
    end else begin
        if (((~(fsm_state_2 == 3'd4) & ~(fsm_state_2 == 3'd1) & ~(fsm_state_2 == 3'd2) & ~(fsm_state_2 == 3'd3) & (tmp_45_nbreadreq_fu_126_p3 == 1'd1) & (grp_nbreadreq_fu_92_p8 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((grp_nbreadreq_fu_92_p8 == 1'd1) & (fsm_state_2 == 3'd4) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((grp_nbreadreq_fu_92_p8 == 1'd1) & (fsm_state_2 == 3'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((grp_nbreadreq_fu_92_p8 == 1'd1) & (fsm_state_2 == 3'd2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((grp_nbreadreq_fu_92_p8 == 1'd1) & (fsm_state_2 == 3'd3) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
            reg_191 <= acc_context_data_recv_from_datamover_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        reg_197 <= 64'd0;
    end else begin
        if (((~(fsm_state_2 == 3'd4) & ~(fsm_state_2 == 3'd1) & ~(fsm_state_2 == 3'd2) & ~(fsm_state_2 == 3'd3) & (tmp_45_nbreadreq_fu_126_p3 == 1'd1) & (grp_nbreadreq_fu_92_p8 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((grp_nbreadreq_fu_92_p8 == 1'd1) & (fsm_state_2 == 3'd4) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((grp_nbreadreq_fu_92_p8 == 1'd1) & (fsm_state_2 == 3'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((grp_nbreadreq_fu_92_p8 == 1'd1) & (fsm_state_2 == 3'd2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((grp_nbreadreq_fu_92_p8 == 1'd1) & (fsm_state_2 == 3'd3) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
            reg_197 <= acc_context_data_recv_from_datamover_TKEEP;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        reg_202 <= 64'd0;
    end else begin
        if (((~(fsm_state_2 == 3'd4) & ~(fsm_state_2 == 3'd1) & ~(fsm_state_2 == 3'd2) & ~(fsm_state_2 == 3'd3) & (tmp_45_nbreadreq_fu_126_p3 == 1'd1) & (grp_nbreadreq_fu_92_p8 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((grp_nbreadreq_fu_92_p8 == 1'd1) & (fsm_state_2 == 3'd4) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((grp_nbreadreq_fu_92_p8 == 1'd1) & (fsm_state_2 == 3'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((grp_nbreadreq_fu_92_p8 == 1'd1) & (fsm_state_2 == 3'd2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((grp_nbreadreq_fu_92_p8 == 1'd1) & (fsm_state_2 == 3'd3) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
            reg_202 <= acc_context_data_recv_from_datamover_TSTRB;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        reg_207 <= 8'd0;
    end else begin
        if (((~(fsm_state_2 == 3'd4) & ~(fsm_state_2 == 3'd1) & ~(fsm_state_2 == 3'd2) & ~(fsm_state_2 == 3'd3) & (tmp_45_nbreadreq_fu_126_p3 == 1'd1) & (grp_nbreadreq_fu_92_p8 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((grp_nbreadreq_fu_92_p8 == 1'd1) & (fsm_state_2 == 3'd4) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((grp_nbreadreq_fu_92_p8 == 1'd1) & (fsm_state_2 == 3'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((grp_nbreadreq_fu_92_p8 == 1'd1) & (fsm_state_2 == 3'd2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((grp_nbreadreq_fu_92_p8 == 1'd1) & (fsm_state_2 == 3'd3) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
            reg_207 <= acc_context_data_recv_from_datamover_TID;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_42_reg_347 <= 1'd0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            tmp_42_reg_347 <= grp_nbreadreq_fu_92_p8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_43_reg_329 <= 1'd0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            tmp_43_reg_329 <= grp_nbreadreq_fu_92_p8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_44_reg_320 <= 1'd0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            tmp_44_reg_320 <= grp_nbreadreq_fu_92_p8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_45_reg_363 <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            tmp_45_reg_363 <= tmp_45_nbreadreq_fu_126_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_reg_359 <= 1'd0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            tmp_reg_359 <= grp_nbreadreq_fu_92_p8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_s_reg_338 <= 1'd0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            tmp_s_reg_338 <= grp_nbreadreq_fu_92_p8;
        end
    end
end

always @ (*) begin
    if ((((ap_predicate_op62_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_predicate_op45_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_predicate_op35_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_predicate_op23_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_predicate_op9_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)))) begin
        acc_context_data_recv_from_datamover_TDATA_blk_n = acc_context_data_recv_from_datamover_TVALID;
    end else begin
        acc_context_data_recv_from_datamover_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_predicate_op62_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op45_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op35_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op23_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op9_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        acc_context_data_recv_from_datamover_TREADY = 1'b1;
    end else begin
        acc_context_data_recv_from_datamover_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op92_write_state2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op89_write_state2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op87_write_state2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op85_write_state2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op82_write_state2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op80_write_state2 == 1'b1)))) begin
        acc_context_data_send_to_acc_TDATA_blk_n = acc_context_data_send_to_acc_TREADY;
    end else begin
        acc_context_data_send_to_acc_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_predicate_op92_write_state2 == 1'b1))) begin
        acc_context_data_send_to_acc_TDEST = context_pkt_dest_1_reg_372;
    end else if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_predicate_op89_write_state2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_predicate_op87_write_state2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_predicate_op85_write_state2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_predicate_op82_write_state2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_predicate_op80_write_state2 == 1'b1)))) begin
        acc_context_data_send_to_acc_TDEST = dest;
    end else begin
        acc_context_data_send_to_acc_TDEST = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_311)) begin
        if ((ap_predicate_op92_write_state2 == 1'b1)) begin
            acc_context_data_send_to_acc_TLAST = context_pkt_last_5_reg_367;
        end else if ((ap_predicate_op89_write_state2 == 1'b1)) begin
            acc_context_data_send_to_acc_TLAST = 1'd1;
        end else if ((ap_predicate_op87_write_state2 == 1'b1)) begin
            acc_context_data_send_to_acc_TLAST = 1'd0;
        end else if ((ap_predicate_op85_write_state2 == 1'b1)) begin
            acc_context_data_send_to_acc_TLAST = context_pkt_last_1_reg_342;
        end else if ((ap_predicate_op82_write_state2 == 1'b1)) begin
            acc_context_data_send_to_acc_TLAST = context_pkt_last_2_reg_333;
        end else if ((ap_predicate_op80_write_state2 == 1'b1)) begin
            acc_context_data_send_to_acc_TLAST = context_pkt_last_4_reg_324;
        end else begin
            acc_context_data_send_to_acc_TLAST = 'bx;
        end
    end else begin
        acc_context_data_send_to_acc_TLAST = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op92_write_state2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op89_write_state2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op87_write_state2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op85_write_state2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op82_write_state2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op80_write_state2 == 1'b1)))) begin
        acc_context_data_send_to_acc_TVALID = 1'b1;
    end else begin
        acc_context_data_send_to_acc_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op83_write_state2 == 1'b1))) begin
        context_add_lists_blk_n = context_add_lists_full_n;
    end else begin
        context_add_lists_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op83_write_state2 == 1'b1))) begin
        context_add_lists_write = 1'b1;
    end else begin
        context_add_lists_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op68_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        tdest_blk_n = tdest_empty_n;
    end else begin
        tdest_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op68_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tdest_read = 1'b1;
    end else begin
        tdest_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_context_data_send_to_acc_TDATA = reg_191;

assign acc_context_data_send_to_acc_TID = reg_207;

assign acc_context_data_send_to_acc_TKEEP = reg_197;

assign acc_context_data_send_to_acc_TSTRB = reg_202;

assign add_ln547_fu_276_p2 = ($signed(available_buf_num) + $signed(64'd18446744073709551615));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (((ap_predicate_op68_read_state1 == 1'b1) & (tdest_empty_n == 1'b0)) | ((ap_predicate_op62_read_state1 == 1'b1) & (1'b0 == acc_context_data_recv_from_datamover_TVALID)) | ((ap_predicate_op45_read_state1 == 1'b1) & (1'b0 == acc_context_data_recv_from_datamover_TVALID)) | ((ap_predicate_op35_read_state1 == 1'b1) & (1'b0 == acc_context_data_recv_from_datamover_TVALID)) | ((ap_predicate_op23_read_state1 == 1'b1) & (1'b0 == acc_context_data_recv_from_datamover_TVALID)) | ((ap_predicate_op9_read_state1 == 1'b1) & (1'b0 == acc_context_data_recv_from_datamover_TVALID)));
end

always @ (*) begin
    ap_block_state2_io = (((1'b0 == acc_context_data_send_to_acc_TREADY) & (ap_predicate_op92_write_state2 == 1'b1)) | ((1'b0 == acc_context_data_send_to_acc_TREADY) & (ap_predicate_op89_write_state2 == 1'b1)) | ((1'b0 == acc_context_data_send_to_acc_TREADY) & (ap_predicate_op87_write_state2 == 1'b1)) | ((1'b0 == acc_context_data_send_to_acc_TREADY) & (ap_predicate_op85_write_state2 == 1'b1)) | ((1'b0 == acc_context_data_send_to_acc_TREADY) & (ap_predicate_op82_write_state2 == 1'b1)) | ((1'b0 == acc_context_data_send_to_acc_TREADY) & (ap_predicate_op80_write_state2 == 1'b1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((1'b0 == acc_context_data_send_to_acc_TREADY) & (ap_predicate_op92_write_state2 == 1'b1)) | ((1'b0 == acc_context_data_send_to_acc_TREADY) & (ap_predicate_op89_write_state2 == 1'b1)) | ((1'b0 == acc_context_data_send_to_acc_TREADY) & (ap_predicate_op87_write_state2 == 1'b1)) | ((1'b0 == acc_context_data_send_to_acc_TREADY) & (ap_predicate_op85_write_state2 == 1'b1)) | ((1'b0 == acc_context_data_send_to_acc_TREADY) & (ap_predicate_op82_write_state2 == 1'b1)) | ((1'b0 == acc_context_data_send_to_acc_TREADY) & (ap_predicate_op80_write_state2 == 1'b1)) | ((ap_predicate_op83_write_state2 == 1'b1) & (context_add_lists_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_311 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001));
end

always @ (*) begin
    ap_condition_434 = ((grp_nbreadreq_fu_92_p8 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_439 = ((fsm_state_2 == 3'd4) & (icmp_ln548_fu_288_p2 == 1'd1) & (grp_fu_183_p1 == 1'd1));
end

always @ (*) begin
    ap_condition_442 = (~(fsm_state_2 == 3'd4) & ~(fsm_state_2 == 3'd1) & ~(fsm_state_2 == 3'd2) & ~(fsm_state_2 == 3'd3) & (tmp_45_nbreadreq_fu_126_p3 == 1'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

always @ (*) begin
    ap_predicate_op23_read_state1 = ((grp_nbreadreq_fu_92_p8 == 1'd1) & (fsm_state_2 == 3'd2));
end

always @ (*) begin
    ap_predicate_op35_read_state1 = ((grp_nbreadreq_fu_92_p8 == 1'd1) & (fsm_state_2 == 3'd1));
end

always @ (*) begin
    ap_predicate_op45_read_state1 = ((grp_nbreadreq_fu_92_p8 == 1'd1) & (fsm_state_2 == 3'd4));
end

always @ (*) begin
    ap_predicate_op62_read_state1 = (~(fsm_state_2 == 3'd4) & ~(fsm_state_2 == 3'd1) & ~(fsm_state_2 == 3'd2) & ~(fsm_state_2 == 3'd3) & (tmp_45_nbreadreq_fu_126_p3 == 1'd1) & (grp_nbreadreq_fu_92_p8 == 1'd1));
end

always @ (*) begin
    ap_predicate_op68_read_state1 = (~(fsm_state_2 == 3'd4) & ~(fsm_state_2 == 3'd1) & ~(fsm_state_2 == 3'd2) & ~(fsm_state_2 == 3'd3) & (tmp_45_nbreadreq_fu_126_p3 == 1'd1) & (grp_nbreadreq_fu_92_p8 == 1'd1));
end

always @ (*) begin
    ap_predicate_op80_write_state2 = ((tmp_44_reg_320 == 1'd1) & (fsm_state_2_load_reg_316 == 3'd3));
end

always @ (*) begin
    ap_predicate_op82_write_state2 = ((fsm_state_2_load_reg_316 == 3'd2) & (tmp_43_reg_329 == 1'd1));
end

always @ (*) begin
    ap_predicate_op83_write_state2 = ((fsm_state_2_load_reg_316 == 3'd2) & (tmp_43_reg_329 == 1'd1));
end

always @ (*) begin
    ap_predicate_op85_write_state2 = ((fsm_state_2_load_reg_316 == 3'd1) & (tmp_s_reg_338 == 1'd1));
end

always @ (*) begin
    ap_predicate_op87_write_state2 = (((fsm_state_2_load_reg_316 == 3'd4) & (context_pkt_last_reg_351 == 1'd0) & (tmp_42_reg_347 == 1'd1)) | ((fsm_state_2_load_reg_316 == 3'd4) & (icmp_ln548_reg_355 == 1'd0) & (tmp_42_reg_347 == 1'd1)));
end

always @ (*) begin
    ap_predicate_op89_write_state2 = ((fsm_state_2_load_reg_316 == 3'd4) & (context_pkt_last_reg_351 == 1'd1) & (icmp_ln548_reg_355 == 1'd1) & (tmp_42_reg_347 == 1'd1));
end

always @ (*) begin
    ap_predicate_op92_write_state2 = (~(fsm_state_2_load_reg_316 == 3'd3) & ~(fsm_state_2_load_reg_316 == 3'd4) & ~(fsm_state_2_load_reg_316 == 3'd1) & ~(fsm_state_2_load_reg_316 == 3'd2) & (tmp_45_reg_363 == 1'd1) & (tmp_reg_359 == 1'd1));
end

always @ (*) begin
    ap_predicate_op9_read_state1 = ((grp_nbreadreq_fu_92_p8 == 1'd1) & (fsm_state_2 == 3'd3));
end

assign context_add_lists_din = reg_191;

assign context_pkt_last_4_fu_226_p2 = (icmp_ln534_fu_220_p2 & acc_context_data_recv_from_datamover_TLAST);

assign grp_fu_183_p1 = acc_context_data_recv_from_datamover_TLAST;

assign grp_nbreadreq_fu_92_p8 = acc_context_data_recv_from_datamover_TVALID;

assign icmp_ln534_fu_220_p2 = ((available_buf_num == 64'd0) ? 1'b1 : 1'b0);

assign icmp_ln548_fu_288_p2 = ((add_ln547_fu_276_p2 == 64'd0) ? 1'b1 : 1'b0);

assign select_ln536_1_fu_240_p3 = ((acc_context_data_recv_from_datamover_TLAST[0:0] == 1'b1) ? select_ln536_fu_232_p3 : 3'd3);

assign select_ln536_fu_232_p3 = ((icmp_ln534_fu_220_p2[0:0] == 1'b1) ? 3'd0 : 3'd4);

assign tmp_45_nbreadreq_fu_126_p3 = tdest_empty_n;

assign trunc_ln521_fu_254_p1 = acc_context_data_recv_from_datamover_TDATA[63:0];

endmodule //AssScheduler_ContextReceiver
