// ==============================================================
// Generated by Vitis HLS v2023.2.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module AssScheduler_CtrlRspHandler (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ctrl_rsp_from_acc_TDATA,
        ctrl_rsp_from_acc_TVALID,
        ctrl_rsp_from_acc_TREADY,
        ctrl_rsp_from_acc_TKEEP,
        ctrl_rsp_from_acc_TSTRB,
        ctrl_rsp_from_acc_TLAST,
        ctrl_rsp_from_acc_TID,
        acc_context_save_TDATA,
        acc_context_save_TVALID,
        acc_context_save_TREADY,
        acc_context_recovery_TDATA,
        acc_context_recovery_TVALID,
        acc_context_recovery_TREADY,
        acc_context_data_send_to_datamover_TDATA,
        acc_context_data_send_to_datamover_TVALID,
        acc_context_data_send_to_datamover_TREADY,
        acc_context_data_send_to_datamover_TKEEP,
        acc_context_data_send_to_datamover_TSTRB,
        acc_context_data_send_to_datamover_TLAST,
        acc_context_data_send_to_datamover_TID,
        acc_context_data_send_to_datamover_TDEST,
        opc_fifo_dout,
        opc_fifo_empty_n,
        opc_fifo_read,
        outstanding_num_fifo_dout,
        outstanding_num_fifo_empty_n,
        outstanding_num_fifo_read,
        tdest_din,
        tdest_full_n,
        tdest_write,
        context_add_lists_dout,
        context_add_lists_empty_n,
        context_add_lists_read,
        cqe_fifo_din,
        cqe_fifo_full_n,
        cqe_fifo_write
);

parameter    ap_ST_fsm_state1 = 20'd1;
parameter    ap_ST_fsm_state2 = 20'd2;
parameter    ap_ST_fsm_state3 = 20'd4;
parameter    ap_ST_fsm_state4 = 20'd8;
parameter    ap_ST_fsm_state5 = 20'd16;
parameter    ap_ST_fsm_state6 = 20'd32;
parameter    ap_ST_fsm_state7 = 20'd64;
parameter    ap_ST_fsm_state8 = 20'd128;
parameter    ap_ST_fsm_state9 = 20'd256;
parameter    ap_ST_fsm_state10 = 20'd512;
parameter    ap_ST_fsm_state11 = 20'd1024;
parameter    ap_ST_fsm_state12 = 20'd2048;
parameter    ap_ST_fsm_state13 = 20'd4096;
parameter    ap_ST_fsm_state14 = 20'd8192;
parameter    ap_ST_fsm_state15 = 20'd16384;
parameter    ap_ST_fsm_state16 = 20'd32768;
parameter    ap_ST_fsm_state17 = 20'd65536;
parameter    ap_ST_fsm_state18 = 20'd131072;
parameter    ap_ST_fsm_state19 = 20'd262144;
parameter    ap_ST_fsm_state20 = 20'd524288;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [511:0] ctrl_rsp_from_acc_TDATA;
input   ctrl_rsp_from_acc_TVALID;
output   ctrl_rsp_from_acc_TREADY;
input  [63:0] ctrl_rsp_from_acc_TKEEP;
input  [63:0] ctrl_rsp_from_acc_TSTRB;
input  [0:0] ctrl_rsp_from_acc_TLAST;
input  [7:0] ctrl_rsp_from_acc_TID;
output  [79:0] acc_context_save_TDATA;
output   acc_context_save_TVALID;
input   acc_context_save_TREADY;
output  [79:0] acc_context_recovery_TDATA;
output   acc_context_recovery_TVALID;
input   acc_context_recovery_TREADY;
output  [511:0] acc_context_data_send_to_datamover_TDATA;
output   acc_context_data_send_to_datamover_TVALID;
input   acc_context_data_send_to_datamover_TREADY;
output  [63:0] acc_context_data_send_to_datamover_TKEEP;
output  [63:0] acc_context_data_send_to_datamover_TSTRB;
output  [0:0] acc_context_data_send_to_datamover_TLAST;
output  [7:0] acc_context_data_send_to_datamover_TID;
output  [7:0] acc_context_data_send_to_datamover_TDEST;
input  [31:0] opc_fifo_dout;
input   opc_fifo_empty_n;
output   opc_fifo_read;
input  [3:0] outstanding_num_fifo_dout;
input   outstanding_num_fifo_empty_n;
output   outstanding_num_fifo_read;
output  [7:0] tdest_din;
input   tdest_full_n;
output   tdest_write;
input  [511:0] context_add_lists_dout;
input   context_add_lists_empty_n;
output   context_add_lists_read;
output  [63:0] cqe_fifo_din;
input   cqe_fifo_full_n;
output   cqe_fifo_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg ctrl_rsp_from_acc_TREADY;
reg[79:0] acc_context_save_TDATA;
reg acc_context_save_TVALID;
reg[79:0] acc_context_recovery_TDATA;
reg acc_context_recovery_TVALID;
reg[511:0] acc_context_data_send_to_datamover_TDATA;
reg acc_context_data_send_to_datamover_TVALID;
reg[0:0] acc_context_data_send_to_datamover_TLAST;
reg opc_fifo_read;
reg outstanding_num_fifo_read;
reg[7:0] tdest_din;
reg tdest_write;
reg context_add_lists_read;
reg[63:0] cqe_fifo_din;
reg cqe_fifo_write;

(* fsm_encoding = "none" *) reg   [19:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
(*mark_debug="true"*)reg   [3:0] fsm_state;
reg   [31:0] opc;
(*mark_debug="true"*)reg   [3:0] outstanding_num;
reg   [17:0] tempcqe;
reg   [31:0] new_bbt;
reg   [31:0] old_bbt;
reg   [15:0] context_counter;
reg   [1:0] query_buffer_num;
reg   [0:0] need_save;
reg   [39:0] old_context_address;
reg   [39:0] new_context_address;
reg   [0:0] query_ops_index;
reg   [1:0] query_buffer_index;
reg   [1:0] tempcqe_payload_buffer_address0;
reg    tempcqe_payload_buffer_ce0;
reg   [3:0] tempcqe_payload_buffer_we0;
wire   [31:0] tempcqe_payload_buffer_d0;
wire   [31:0] tempcqe_payload_buffer_q0;
reg    ctrl_rsp_from_acc_TDATA_blk_n;
wire   [0:0] grp_nbreadreq_fu_329_p7;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state2;
reg    acc_context_save_TDATA_blk_n;
wire   [0:0] and_ln297_fu_1213_p2;
wire   [0:0] and_ln310_fu_1315_p2;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state14;
reg   [0:0] tmp_2_reg_2334;
wire   [0:0] icmp_ln356_fu_1804_p2;
reg    acc_context_recovery_TDATA_blk_n;
wire    ap_CS_fsm_state16;
reg   [0:0] and_ln297_reg_2409;
wire   [0:0] or_ln320_fu_2016_p2;
reg   [0:0] icmp_ln374_reg_2330;
wire   [0:0] icmp_ln384_fu_1680_p2;
wire    ap_CS_fsm_state8;
reg    acc_context_data_send_to_datamover_TDATA_blk_n;
wire    ap_CS_fsm_state10;
reg   [0:0] tmp_3_reg_2326;
reg    opc_fifo_blk_n;
wire   [0:0] tmp_nbreadreq_fu_408_p3;
wire   [0:0] tmp_8_nbreadreq_fu_416_p3;
reg    outstanding_num_fifo_blk_n;
reg    tdest_blk_n;
reg    context_add_lists_blk_n;
wire   [0:0] tmp_4_nbreadreq_fu_386_p3;
reg    cqe_fifo_blk_n;
wire    ap_CS_fsm_state19;
wire   [31:0] grp_fu_702_p2;
reg   [31:0] reg_712;
reg   [31:0] opc_load_reg_2246;
reg   [31:0] new_bbt_load_reg_2251;
reg   [15:0] context_counter_load_reg_2263;
wire   [0:0] icmp_ln390_1_fu_762_p2;
reg   [0:0] icmp_ln390_1_reg_2268;
reg   [0:0] tmp_4_reg_2286;
wire   [63:0] empty_152_fu_962_p1;
reg   [63:0] empty_152_reg_2290;
reg   [39:0] p_cast1_reg_2296;
reg   [39:0] p_cast2_reg_2301;
reg   [39:0] p_cast3_reg_2306;
reg   [39:0] p_cast4_reg_2311;
reg   [39:0] p_cast5_reg_2316;
reg   [39:0] p_cast6_reg_2321;
wire   [0:0] icmp_ln374_fu_1060_p2;
wire   [63:0] available_buf_num_1_fu_1066_p1;
reg   [63:0] available_buf_num_1_reg_2345;
reg   [39:0] trunc_ln337_2_reg_2350;
reg   [39:0] trunc_ln337_3_reg_2355;
reg   [39:0] trunc_ln337_4_reg_2360;
reg   [39:0] trunc_ln337_5_reg_2365;
reg   [39:0] trunc_ln337_6_reg_2370;
reg   [39:0] trunc_ln337_7_reg_2375;
reg   [0:0] tmp_1_reg_2380;
reg   [7:0] rsp_reg_2384;
wire   [3:0] add_ln293_fu_1189_p2;
reg   [3:0] add_ln293_reg_2392;
wire   [0:0] icmp_ln297_fu_1201_p2;
reg   [0:0] icmp_ln297_reg_2397;
wire   [0:0] icmp_ln297_1_fu_1207_p2;
reg   [0:0] icmp_ln297_1_reg_2403;
reg   [31:0] trunc_ln3_reg_2418;
wire   [31:0] trunc_ln4_fu_1239_p4;
reg   [31:0] trunc_ln4_reg_2424;
wire   [0:0] icmp_ln300_fu_1265_p2;
reg   [0:0] icmp_ln300_reg_2429;
reg   [39:0] mem_req_saddr_2_reg_2435;
wire   [0:0] pkt_last_1_fu_1416_p2;
reg   [0:0] pkt_last_1_reg_2443;
wire   [0:0] icmp_ln405_fu_1547_p2;
reg   [0:0] icmp_ln405_reg_2459;
wire    ap_CS_fsm_state6;
wire   [63:0] add_ln405_fu_1552_p2;
reg   [63:0] add_ln405_reg_2470;
wire    ap_CS_fsm_state7;
reg   [511:0] context_pkt_3_reg_2483;
wire   [0:0] icmp_ln327_fu_2105_p2;
reg   [0:0] icmp_ln327_reg_2502;
wire   [0:0] icmp_ln327_3_fu_2110_p2;
reg   [0:0] icmp_ln327_3_reg_2510;
wire   [0:0] and_ln327_2_fu_2131_p2;
reg   [0:0] and_ln327_2_reg_2515;
wire    ap_CS_fsm_state17;
wire   [0:0] and_ln327_6_fu_2164_p2;
reg   [0:0] and_ln327_6_reg_2520;
reg   [2:0] rsp_data_address0;
reg    rsp_data_ce0;
reg    rsp_data_we0;
reg   [39:0] rsp_data_d0;
wire   [39:0] rsp_data_q0;
reg   [2:0] rsp_data_address1;
reg    rsp_data_ce1;
reg    rsp_data_we1;
reg   [39:0] rsp_data_d1;
reg   [2:0] addlists_address0;
reg    addlists_ce0;
reg    addlists_we0;
reg   [39:0] addlists_d0;
wire   [39:0] addlists_q0;
reg   [2:0] addlists_address1;
reg    addlists_ce1;
reg    addlists_we1;
reg   [39:0] addlists_d1;
reg   [31:0] old_bbt_loc_1_reg_634;
reg    ap_block_state2;
reg    ap_predicate_op60_read_state1;
reg    ap_predicate_op88_read_state1;
reg    ap_predicate_op94_write_state1;
reg    ap_predicate_op105_read_state1;
reg    ap_predicate_op129_read_state1;
reg    ap_predicate_op144_write_state1;
reg    ap_predicate_op148_read_state1;
reg    ap_predicate_op193_write_state1;
reg    ap_predicate_op208_read_state1;
reg    ap_predicate_op210_read_state1;
reg    ap_block_state1;
reg    ap_block_state1_io;
reg   [0:0] p_0193_reg_643;
reg    ap_predicate_op294_write_state9;
reg    ap_predicate_op295_write_state9;
reg    ap_block_state9;
reg    ap_block_state9_io;
reg   [5:0] storemerge_reg_657;
reg   [31:0] new_bbt_loc_0_reg_670;
reg    ap_predicate_op371_write_state16;
reg    ap_predicate_op372_write_state16;
reg    ap_block_state16;
reg    ap_block_state16_io;
reg   [31:0] old_bbt_loc_0_reg_679;
reg   [0:0] need_save_loc_0_reg_688;
wire   [63:0] zext_ln453_fu_815_p1;
wire   [63:0] zext_ln471_fu_1434_p1;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln405_1_fu_1566_p2;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire   [63:0] add_ln357_fu_1809_p2;
wire   [3:0] select_ln327_3_fu_2217_p3;
wire   [3:0] select_ln390_1_fu_1787_p3;
wire   [3:0] select_ln416_fu_1582_p3;
wire   [3:0] select_ln435_fu_1533_p3;
wire   [3:0] select_ln467_fu_793_p3;
wire   [3:0] select_ln460_fu_902_p3;
wire   [3:0] select_ln444_1_fu_930_p3;
wire   [3:0] select_ln473_fu_1439_p3;
wire    ap_CS_fsm_state18;
reg    ap_predicate_op337_write_state14;
reg    ap_block_state14;
reg    ap_block_state14_io;
wire    ap_CS_fsm_state3;
wire   [17:0] zext_ln292_fu_1161_p1;
wire  signed [17:0] sext_ln290_fu_1179_p1;
wire   [17:0] zext_ln283_fu_1479_p1;
wire   [15:0] trunc_ln1_fu_1151_p4;
wire   [15:0] zext_ln318_fu_2001_p1;
wire   [15:0] select_ln427_fu_1513_p3;
wire   [15:0] add_ln370_fu_1048_p2;
wire   [1:0] add_ln459_fu_890_p2;
wire   [0:0] query_ops_index_load_load_fu_820_p1;
wire   [39:0] trunc_ln6_fu_1277_p4;
wire   [0:0] xor_ln457_fu_878_p2;
wire   [1:0] add_ln471_fu_1422_p2;
reg   [63:0] i_fu_314;
reg   [63:0] i_1_fu_318;
wire   [63:0] add_ln405_1_fu_1571_p2;
wire   [63:0] zext_ln466_fu_782_p1;
wire   [63:0] zext_ln472_fu_2238_p1;
reg    ap_block_state10;
wire   [0:0] or_ln427_fu_1506_p2;
reg    ap_block_state10_io;
wire   [79:0] zext_ln314_fu_1407_p1;
wire   [79:0] zext_ln362_fu_1905_p1;
wire   [79:0] zext_ln358_fu_1996_p1;
wire   [79:0] zext_ln414_fu_1675_p1;
wire   [79:0] zext_ln387_fu_1769_p1;
wire   [79:0] zext_ln323_fu_2100_p1;
wire   [3:0] shl_ln454_fu_852_p2;
wire   [39:0] empty_153_fu_966_p1;
wire   [39:0] trunc_ln337_8_fu_1070_p1;
wire   [0:0] pkt_last_fu_768_p2;
wire   [31:0] zext_ln327_fu_733_p1;
wire   [32:0] tmp_s_fu_774_p3;
wire   [0:0] icmp_ln467_fu_787_p2;
wire   [7:0] trunc_ln454_fu_832_p1;
wire   [15:0] bf_set1_fu_836_p3;
wire   [1:0] shl_ln_fu_824_p3;
wire   [3:0] zext_ln454_1_fu_848_p1;
wire   [4:0] shl_ln454_2_fu_859_p3;
wire   [31:0] zext_ln454_fu_844_p1;
wire   [31:0] zext_ln454_2_fu_867_p1;
wire   [0:0] icmp_ln444_fu_916_p2;
wire   [3:0] select_ln444_fu_922_p3;
wire   [15:0] trunc_ln327_fu_737_p1;
wire   [16:0] or_ln1_fu_1171_p3;
wire   [7:0] trunc_ln5_fu_1255_p4;
wire   [0:0] icmp_ln310_fu_1309_p2;
wire   [39:0] mem_req_saddr_1_fu_1321_p2;
wire   [103:0] shl_ln5_fu_1327_p3;
wire   [103:0] or_ln314_fu_1335_p2;
wire   [39:0] tmp_34_fu_1375_p4;
wire   [0:0] tmp_32_fu_1359_p3;
wire   [0:0] tmp_33_fu_1367_p3;
wire   [5:0] tmp_31_fu_1349_p4;
wire   [0:0] tmp_30_fu_1341_p3;
wire   [71:0] tmp13_fu_1385_p7;
wire   [71:0] or_ln314_1_fu_1401_p2;
wire   [7:0] trunc_ln327_1_fu_741_p1;
wire   [16:0] zext_ln283_cast_fu_1471_p3;
wire   [15:0] add_ln423_fu_1489_p2;
wire   [0:0] icmp_ln427_fu_1494_p2;
wire   [0:0] icmp_ln427_1_fu_1500_p2;
wire   [0:0] icmp_ln435_fu_1527_p2;
wire   [103:0] shl_ln4_fu_1595_p3;
wire   [103:0] or_ln414_fu_1603_p2;
wire   [39:0] tmp_29_fu_1643_p4;
wire   [0:0] tmp_27_fu_1627_p3;
wire   [0:0] tmp_28_fu_1635_p3;
wire   [5:0] tmp_26_fu_1617_p4;
wire   [0:0] tmp_25_fu_1609_p3;
wire   [71:0] tmp26_fu_1653_p7;
wire   [71:0] or_ln414_1_fu_1669_p2;
wire   [103:0] shl_ln3_fu_1689_p3;
wire   [103:0] or_ln387_fu_1697_p2;
wire   [39:0] tmp_24_fu_1737_p4;
wire   [0:0] tmp_22_fu_1721_p3;
wire   [0:0] tmp_23_fu_1729_p3;
wire   [5:0] tmp_21_fu_1711_p4;
wire   [0:0] tmp_20_fu_1703_p3;
wire   [71:0] tmp21_fu_1747_p7;
wire   [71:0] or_ln387_1_fu_1763_p2;
wire   [0:0] icmp_ln390_fu_1774_p2;
wire   [3:0] select_ln390_fu_1780_p3;
wire   [103:0] shl_ln1_fu_1825_p3;
wire   [103:0] or_ln362_fu_1833_p2;
wire   [39:0] tmp_14_fu_1873_p4;
wire   [0:0] tmp_12_fu_1857_p3;
wire   [0:0] tmp_13_fu_1865_p3;
wire   [5:0] tmp_11_fu_1847_p4;
wire   [0:0] tmp_10_fu_1839_p3;
wire   [71:0] tmp11_fu_1883_p7;
wire   [71:0] or_ln362_1_fu_1899_p2;
wire   [103:0] shl_ln2_fu_1916_p3;
wire   [103:0] or_ln358_fu_1924_p2;
wire   [39:0] tmp_19_fu_1964_p4;
wire   [0:0] tmp_17_fu_1948_p3;
wire   [0:0] tmp_18_fu_1956_p3;
wire   [5:0] tmp_16_fu_1938_p4;
wire   [0:0] tmp_15_fu_1930_p3;
wire   [71:0] tmp16_fu_1974_p7;
wire   [71:0] or_ln358_1_fu_1990_p2;
wire   [0:0] icmp_ln320_fu_2011_p2;
wire   [103:0] shl_ln6_fu_2021_p3;
wire   [103:0] or_ln323_fu_2028_p2;
wire   [39:0] tmp_39_fu_2068_p4;
wire   [0:0] tmp_37_fu_2052_p3;
wire   [0:0] tmp_38_fu_2060_p3;
wire   [5:0] tmp_36_fu_2042_p4;
wire   [0:0] tmp_35_fu_2034_p3;
wire   [71:0] tmp19_fu_2078_p7;
wire   [71:0] or_ln323_1_fu_2094_p2;
wire   [0:0] icmp_ln327_1_fu_2115_p2;
wire   [0:0] and_ln327_1_fu_2126_p2;
wire   [0:0] and_ln327_fu_2121_p2;
wire   [0:0] or_ln327_fu_2143_p2;
wire   [0:0] xor_ln327_1_fu_2148_p2;
wire   [0:0] icmp_ln327_2_fu_2137_p2;
wire   [0:0] and_ln327_5_fu_2159_p2;
wire   [0:0] and_ln327_4_fu_2154_p2;
wire   [0:0] xor_ln327_fu_2170_p2;
wire   [0:0] and_ln327_3_fu_2175_p2;
wire   [0:0] or_ln327_1_fu_2187_p2;
wire   [3:0] select_ln327_fu_2180_p3;
wire   [3:0] select_ln327_1_fu_2192_p3;
wire   [0:0] or_ln327_2_fu_2199_p2;
wire   [0:0] or_ln327_3_fu_2211_p2;
wire   [3:0] select_ln327_2_fu_2203_p3;
wire   [32:0] tmp_9_fu_2231_p3;
wire    ap_CS_fsm_state20;
reg   [19:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
reg    ap_condition_248;
reg    ap_condition_463;
reg    ap_condition_485;
reg    ap_condition_651;
reg    ap_condition_643;
reg    ap_condition_647;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 20'd1;
#0 fsm_state = 4'd0;
#0 opc = 32'd0;
#0 outstanding_num = 4'd0;
#0 tempcqe = 18'd0;
#0 new_bbt = 32'd0;
#0 old_bbt = 32'd0;
#0 context_counter = 16'd0;
#0 query_buffer_num = 2'd0;
#0 need_save = 1'd0;
#0 old_context_address = 40'd0;
#0 new_context_address = 40'd0;
#0 query_ops_index = 1'd0;
#0 query_buffer_index = 2'd0;
#0 tmp_2_reg_2334 = 1'd0;
#0 and_ln297_reg_2409 = 1'd0;
#0 icmp_ln374_reg_2330 = 1'd0;
#0 tmp_3_reg_2326 = 1'd0;
#0 reg_712 = 32'd0;
#0 opc_load_reg_2246 = 32'd0;
#0 new_bbt_load_reg_2251 = 32'd0;
#0 context_counter_load_reg_2263 = 16'd0;
#0 icmp_ln390_1_reg_2268 = 1'd0;
#0 tmp_4_reg_2286 = 1'd0;
#0 empty_152_reg_2290 = 64'd0;
#0 p_cast1_reg_2296 = 40'd0;
#0 p_cast2_reg_2301 = 40'd0;
#0 p_cast3_reg_2306 = 40'd0;
#0 p_cast4_reg_2311 = 40'd0;
#0 p_cast5_reg_2316 = 40'd0;
#0 p_cast6_reg_2321 = 40'd0;
#0 available_buf_num_1_reg_2345 = 64'd0;
#0 trunc_ln337_2_reg_2350 = 40'd0;
#0 trunc_ln337_3_reg_2355 = 40'd0;
#0 trunc_ln337_4_reg_2360 = 40'd0;
#0 trunc_ln337_5_reg_2365 = 40'd0;
#0 trunc_ln337_6_reg_2370 = 40'd0;
#0 trunc_ln337_7_reg_2375 = 40'd0;
#0 tmp_1_reg_2380 = 1'd0;
#0 rsp_reg_2384 = 8'd0;
#0 add_ln293_reg_2392 = 4'd0;
#0 icmp_ln297_reg_2397 = 1'd0;
#0 icmp_ln297_1_reg_2403 = 1'd0;
#0 trunc_ln3_reg_2418 = 32'd0;
#0 trunc_ln4_reg_2424 = 32'd0;
#0 icmp_ln300_reg_2429 = 1'd0;
#0 mem_req_saddr_2_reg_2435 = 40'd0;
#0 pkt_last_1_reg_2443 = 1'd0;
#0 icmp_ln405_reg_2459 = 1'd0;
#0 add_ln405_reg_2470 = 64'd0;
#0 context_pkt_3_reg_2483 = 512'd0;
#0 icmp_ln327_reg_2502 = 1'd0;
#0 icmp_ln327_3_reg_2510 = 1'd0;
#0 and_ln327_2_reg_2515 = 1'd0;
#0 and_ln327_6_reg_2520 = 1'd0;
#0 old_bbt_loc_1_reg_634 = 32'd0;
#0 p_0193_reg_643 = 1'd0;
#0 storemerge_reg_657 = 6'd0;
#0 new_bbt_loc_0_reg_670 = 32'd0;
#0 old_bbt_loc_0_reg_679 = 32'd0;
#0 need_save_loc_0_reg_688 = 1'd0;
#0 i_fu_314 = 64'd0;
#0 i_1_fu_318 = 64'd0;
end

AssScheduler_CtrlRspHandler_tempcqe_payload_buffer_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
tempcqe_payload_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tempcqe_payload_buffer_address0),
    .ce0(tempcqe_payload_buffer_ce0),
    .we0(tempcqe_payload_buffer_we0),
    .d0(tempcqe_payload_buffer_d0),
    .q0(tempcqe_payload_buffer_q0)
);

AssScheduler_CtrlRspHandler_rsp_data_RAM_AUTO_1R1W #(
    .DataWidth( 40 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
rsp_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(rsp_data_address0),
    .ce0(rsp_data_ce0),
    .we0(rsp_data_we0),
    .d0(rsp_data_d0),
    .q0(rsp_data_q0),
    .address1(rsp_data_address1),
    .ce1(rsp_data_ce1),
    .we1(rsp_data_we1),
    .d1(rsp_data_d1)
);

AssScheduler_CtrlRspHandler_rsp_data_RAM_AUTO_1R1W #(
    .DataWidth( 40 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
addlists_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(addlists_address0),
    .ce0(addlists_ce0),
    .we0(addlists_we0),
    .d0(addlists_d0),
    .q0(addlists_q0),
    .address1(addlists_address1),
    .ce1(addlists_ce1),
    .we1(addlists_we1),
    .d1(addlists_d1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        add_ln293_reg_2392 <= 4'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            add_ln293_reg_2392 <= add_ln293_fu_1189_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        add_ln405_reg_2470 <= 64'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            add_ln405_reg_2470 <= add_ln405_fu_1552_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        and_ln297_reg_2409 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            and_ln297_reg_2409 <= and_ln297_fu_1213_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        and_ln327_2_reg_2515 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state17)) begin
            and_ln327_2_reg_2515 <= and_ln327_2_fu_2131_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        and_ln327_6_reg_2520 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state17)) begin
            and_ln327_6_reg_2520 <= and_ln327_6_fu_2164_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        available_buf_num_1_reg_2345 <= 64'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            available_buf_num_1_reg_2345 <= available_buf_num_1_fu_1066_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        context_counter <= 16'd0;
    end else begin
        if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd4))) begin
            context_counter <= add_ln370_fu_1048_p2;
        end else if (((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (fsm_state == 4'd5)) | (~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd7)))) begin
            context_counter <= 16'd0;
        end else if ((~((1'b0 == acc_context_data_send_to_datamover_TREADY) | (1'b1 == ap_block_state2)) & (1'b1 == ap_CS_fsm_state2))) begin
            context_counter <= select_ln427_fu_1513_p3;
        end else if ((~((1'b1 == ap_block_state16_io) | (1'b1 == ap_block_state16)) & (1'b1 == ap_CS_fsm_state16) & (1'd1 == and_ln297_reg_2409))) begin
            context_counter <= zext_ln318_fu_2001_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        context_counter_load_reg_2263 <= 16'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            context_counter_load_reg_2263 <= context_counter;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        context_pkt_3_reg_2483 <= 512'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            context_pkt_3_reg_2483 <= ctrl_rsp_from_acc_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        empty_152_reg_2290 <= 64'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            empty_152_reg_2290 <= empty_152_fu_962_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        fsm_state <= 4'd0;
    end else begin
        if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & ~(fsm_state == 4'd8) & ~(fsm_state == 4'd6) & ~(fsm_state == 4'd5) & ~(fsm_state == 4'd4) & ~(fsm_state == 4'd9) & ~(fsm_state == 4'd2) & ~(fsm_state == 4'd7) & ~(fsm_state == 4'd3) & ~(fsm_state == 4'd1) & (tmp_8_nbreadreq_fu_416_p3 == 1'd1) & (tmp_nbreadreq_fu_408_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            fsm_state <= 4'd1;
        end else if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (fsm_state == 4'd9))) begin
            fsm_state <= select_ln473_fu_1439_p3;
        end else if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd7))) begin
            fsm_state <= select_ln444_1_fu_930_p3;
        end else if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd2))) begin
            fsm_state <= select_ln460_fu_902_p3;
        end else if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (fsm_state == 4'd8))) begin
            fsm_state <= select_ln467_fu_793_p3;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            fsm_state <= select_ln435_fu_1533_p3;
        end else if (((1'b1 == ap_CS_fsm_state7) & (((icmp_ln405_reg_2459 == 1'd1) & (tmp_4_reg_2286 == 1'd1)) | ((icmp_ln405_1_fu_1566_p2 == 1'd1) & (tmp_4_reg_2286 == 1'd1))))) begin
            fsm_state <= select_ln416_fu_1582_p3;
        end else if ((~((1'b1 == ap_block_state9_io) | (1'b1 == ap_block_state9)) & (1'b1 == ap_CS_fsm_state9) & (icmp_ln374_reg_2330 == 1'd1))) begin
            fsm_state <= select_ln390_1_fu_1787_p3;
        end else if ((~((1'b1 == ap_block_state14_io) | (1'b1 == ap_block_state14)) & (1'b1 == ap_CS_fsm_state14) & (icmp_ln356_fu_1804_p2 == 1'd1) & (tmp_2_reg_2334 == 1'd1))) begin
            fsm_state <= 4'd4;
        end else if (((tmp_1_reg_2380 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
            fsm_state <= select_ln327_3_fu_2217_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        i_1_fu_318 <= 64'd0;
    end else begin
        if (((icmp_ln405_fu_1547_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
            i_1_fu_318 <= 64'd1;
        end else if (((icmp_ln405_1_fu_1566_p2 == 1'd0) & (icmp_ln405_reg_2459 == 1'd0) & (tmp_4_reg_2286 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
            i_1_fu_318 <= add_ln405_1_fu_1571_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        i_fu_314 <= 64'd0;
    end else begin
        if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd3))) begin
            i_fu_314 <= 64'd0;
        end else if ((~((1'b1 == ap_block_state14_io) | (1'b1 == ap_block_state14)) & (1'b1 == ap_CS_fsm_state14) & (icmp_ln356_fu_1804_p2 == 1'd0) & (tmp_2_reg_2334 == 1'd1))) begin
            i_fu_314 <= add_ln357_fu_1809_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln297_1_reg_2403 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            icmp_ln297_1_reg_2403 <= icmp_ln297_1_fu_1207_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln297_reg_2397 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            icmp_ln297_reg_2397 <= icmp_ln297_fu_1201_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln300_reg_2429 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            icmp_ln300_reg_2429 <= icmp_ln300_fu_1265_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln327_3_reg_2510 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state16)) begin
            icmp_ln327_3_reg_2510 <= icmp_ln327_3_fu_2110_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln327_reg_2502 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state16)) begin
            icmp_ln327_reg_2502 <= icmp_ln327_fu_2105_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln374_reg_2330 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            icmp_ln374_reg_2330 <= icmp_ln374_fu_1060_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln390_1_reg_2268 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            icmp_ln390_1_reg_2268 <= icmp_ln390_1_fu_762_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln405_reg_2459 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            icmp_ln405_reg_2459 <= icmp_ln405_fu_1547_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        mem_req_saddr_2_reg_2435 <= 40'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            mem_req_saddr_2_reg_2435 <= {{ctrl_rsp_from_acc_TDATA[215:176]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        need_save <= 1'd0;
    end else begin
        if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (1'd1 == and_ln297_fu_1213_p2) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd1))) begin
            need_save <= icmp_ln300_fu_1265_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        need_save_loc_0_reg_688 <= 1'd0;
    end else begin
        if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'd0 == and_ln297_fu_1213_p2) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd1))) begin
            need_save_loc_0_reg_688 <= need_save;
        end else if ((~((1'b1 == ap_block_state16_io) | (1'b1 == ap_block_state16)) & (1'b1 == ap_CS_fsm_state16) & (1'd1 == and_ln297_reg_2409))) begin
            need_save_loc_0_reg_688 <= icmp_ln300_reg_2429;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        new_bbt <= 32'd0;
    end else begin
        if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (1'd1 == and_ln297_fu_1213_p2) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd1))) begin
            new_bbt <= {{ctrl_rsp_from_acc_TDATA[111:80]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        new_bbt_load_reg_2251 <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            new_bbt_load_reg_2251 <= new_bbt;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        new_bbt_loc_0_reg_670 <= 32'd0;
    end else begin
        if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'd0 == and_ln297_fu_1213_p2) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd1))) begin
            new_bbt_loc_0_reg_670 <= new_bbt;
        end else if ((~((1'b1 == ap_block_state16_io) | (1'b1 == ap_block_state16)) & (1'b1 == ap_CS_fsm_state16) & (1'd1 == and_ln297_reg_2409))) begin
            new_bbt_loc_0_reg_670 <= trunc_ln3_reg_2418;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        new_context_address <= 40'd0;
    end else begin
        if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (1'd1 == and_ln297_fu_1213_p2) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd1))) begin
            new_context_address <= {{ctrl_rsp_from_acc_TDATA[215:176]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        old_bbt <= 32'd0;
    end else begin
        if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (1'd1 == and_ln297_fu_1213_p2) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd1))) begin
            old_bbt <= {{ctrl_rsp_from_acc_TDATA[79:48]}};
        end else if (((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd6)) | (~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd4)))) begin
            old_bbt <= grp_fu_702_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        old_bbt_loc_0_reg_679 <= 32'd0;
    end else begin
        if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'd0 == and_ln297_fu_1213_p2) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd1))) begin
            old_bbt_loc_0_reg_679 <= old_bbt;
        end else if ((~((1'b1 == ap_block_state16_io) | (1'b1 == ap_block_state16)) & (1'b1 == ap_CS_fsm_state16) & (1'd1 == and_ln297_reg_2409))) begin
            old_bbt_loc_0_reg_679 <= trunc_ln4_reg_2424;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        old_bbt_loc_1_reg_634 <= 32'd0;
    end else begin
        if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd0) & (fsm_state == 4'd6))) begin
            old_bbt_loc_1_reg_634 <= old_bbt;
        end else if ((~((1'b0 == acc_context_data_send_to_datamover_TREADY) | (1'b1 == ap_block_state2)) & (1'b1 == ap_CS_fsm_state2))) begin
            old_bbt_loc_1_reg_634 <= reg_712;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        old_context_address <= 40'd0;
    end else begin
        if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (1'd1 == and_ln297_fu_1213_p2) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd1))) begin
            old_context_address <= {{ctrl_rsp_from_acc_TDATA[151:112]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        opc <= 32'd0;
    end else begin
        if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & ~(fsm_state == 4'd8) & ~(fsm_state == 4'd6) & ~(fsm_state == 4'd5) & ~(fsm_state == 4'd4) & ~(fsm_state == 4'd9) & ~(fsm_state == 4'd2) & ~(fsm_state == 4'd7) & ~(fsm_state == 4'd3) & ~(fsm_state == 4'd1) & (tmp_8_nbreadreq_fu_416_p3 == 1'd1) & (tmp_nbreadreq_fu_408_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            opc <= opc_fifo_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        opc_load_reg_2246 <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            opc_load_reg_2246 <= opc;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        outstanding_num <= 4'd0;
    end else begin
        if ((1'b1 == ap_condition_463)) begin
            if ((1'b1 == ap_condition_248)) begin
                outstanding_num <= outstanding_num_fifo_dout;
            end else if (((grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd1))) begin
                outstanding_num <= add_ln293_fu_1189_p2;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        p_0193_reg_643 <= 1'd0;
    end else begin
        if ((1'b1 == ap_condition_485)) begin
            if ((icmp_ln374_reg_2330 == 1'd1)) begin
                p_0193_reg_643 <= 1'd1;
            end else if ((icmp_ln374_reg_2330 == 1'd0)) begin
                p_0193_reg_643 <= 1'd0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        p_cast1_reg_2296 <= 40'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            p_cast1_reg_2296 <= {{context_add_lists_dout[167:128]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        p_cast2_reg_2301 <= 40'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            p_cast2_reg_2301 <= {{context_add_lists_dout[231:192]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        p_cast3_reg_2306 <= 40'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            p_cast3_reg_2306 <= {{context_add_lists_dout[295:256]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        p_cast4_reg_2311 <= 40'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            p_cast4_reg_2311 <= {{context_add_lists_dout[359:320]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        p_cast5_reg_2316 <= 40'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            p_cast5_reg_2316 <= {{context_add_lists_dout[423:384]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        p_cast6_reg_2321 <= 40'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            p_cast6_reg_2321 <= {{context_add_lists_dout[487:448]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        pkt_last_1_reg_2443 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            pkt_last_1_reg_2443 <= pkt_last_1_fu_1416_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        query_buffer_index <= 2'd0;
    end else begin
        if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (fsm_state == 4'd9))) begin
            query_buffer_index <= add_ln471_fu_1422_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        query_buffer_num <= 2'd0;
    end else begin
        if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (query_ops_index_load_load_fu_820_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd2))) begin
            query_buffer_num <= add_ln459_fu_890_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        query_ops_index <= 1'd0;
    end else begin
        if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd2))) begin
            query_ops_index <= xor_ln457_fu_878_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        reg_712 <= 32'd0;
    end else begin
        if ((((1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd6)) | ((1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd4)))) begin
            reg_712 <= grp_fu_702_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        rsp_reg_2384 <= 8'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            rsp_reg_2384 <= ctrl_rsp_from_acc_TID;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                storemerge_reg_657[5] <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_651)) begin
            if ((1'd0 == and_ln310_fu_1315_p2)) begin
                                storemerge_reg_657[5] <= 1'b0;
            end else if ((1'd1 == and_ln310_fu_1315_p2)) begin
                                storemerge_reg_657[5] <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tempcqe <= 18'd0;
    end else begin
        if ((1'b1 == ap_condition_463)) begin
            if ((1'b1 == ap_condition_248)) begin
                tempcqe <= zext_ln283_fu_1479_p1;
            end else if ((1'b1 == ap_condition_647)) begin
                tempcqe <= sext_ln290_fu_1179_p1;
            end else if ((1'b1 == ap_condition_643)) begin
                tempcqe <= zext_ln292_fu_1161_p1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_1_reg_2380 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            tmp_1_reg_2380 <= grp_nbreadreq_fu_329_p7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_2_reg_2334 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            tmp_2_reg_2334 <= grp_nbreadreq_fu_329_p7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_3_reg_2326 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            tmp_3_reg_2326 <= grp_nbreadreq_fu_329_p7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_4_reg_2286 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            tmp_4_reg_2286 <= tmp_4_nbreadreq_fu_386_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        trunc_ln337_2_reg_2350 <= 40'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            trunc_ln337_2_reg_2350 <= {{ctrl_rsp_from_acc_TDATA[167:128]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        trunc_ln337_3_reg_2355 <= 40'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            trunc_ln337_3_reg_2355 <= {{ctrl_rsp_from_acc_TDATA[231:192]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        trunc_ln337_4_reg_2360 <= 40'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            trunc_ln337_4_reg_2360 <= {{ctrl_rsp_from_acc_TDATA[295:256]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        trunc_ln337_5_reg_2365 <= 40'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            trunc_ln337_5_reg_2365 <= {{ctrl_rsp_from_acc_TDATA[359:320]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        trunc_ln337_6_reg_2370 <= 40'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            trunc_ln337_6_reg_2370 <= {{ctrl_rsp_from_acc_TDATA[423:384]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        trunc_ln337_7_reg_2375 <= 40'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            trunc_ln337_7_reg_2375 <= {{ctrl_rsp_from_acc_TDATA[487:448]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        trunc_ln3_reg_2418 <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            trunc_ln3_reg_2418 <= {{ctrl_rsp_from_acc_TDATA[111:80]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        trunc_ln4_reg_2424 <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            trunc_ln4_reg_2424 <= {{ctrl_rsp_from_acc_TDATA[79:48]}};
        end
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state10) & (tmp_3_reg_2326 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
        acc_context_data_send_to_datamover_TDATA = context_pkt_3_reg_2483;
    end else if ((((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2)) | ((1'b0 == ap_block_state1) & (ap_predicate_op144_write_state1 == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1) & (ap_predicate_op94_write_state1 == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_context_data_send_to_datamover_TDATA = ctrl_rsp_from_acc_TDATA;
    end else begin
        acc_context_data_send_to_datamover_TDATA = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((tmp_3_reg_2326 == 1'd1) & (1'b1 == ap_CS_fsm_state10)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd7)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd3)))) begin
        acc_context_data_send_to_datamover_TDATA_blk_n = acc_context_data_send_to_datamover_TREADY;
    end else begin
        acc_context_data_send_to_datamover_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state10) & (tmp_3_reg_2326 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
        acc_context_data_send_to_datamover_TLAST = p_0193_reg_643;
    end else if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2))) begin
        acc_context_data_send_to_datamover_TLAST = or_ln427_fu_1506_p2;
    end else if (((1'b0 == ap_block_state1) & (ap_predicate_op144_write_state1 == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_context_data_send_to_datamover_TLAST = 1'd0;
    end else if (((1'b0 == ap_block_state1) & (ap_predicate_op94_write_state1 == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_context_data_send_to_datamover_TLAST = 1'd1;
    end else begin
        acc_context_data_send_to_datamover_TLAST = 'bx;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state10_io) | (1'b1 == ap_block_state10)) & (tmp_3_reg_2326 == 1'd1) & (1'b1 == ap_CS_fsm_state10)) | (~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (ap_predicate_op144_write_state1 == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | (~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (ap_predicate_op94_write_state1 == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | (~((1'b0 == acc_context_data_send_to_datamover_TREADY) | (1'b1 == ap_block_state2)) & (1'b1 == ap_CS_fsm_state2)))) begin
        acc_context_data_send_to_datamover_TVALID = 1'b1;
    end else begin
        acc_context_data_send_to_datamover_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state16) & (ap_predicate_op371_write_state16 == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
        acc_context_recovery_TDATA = zext_ln323_fu_2100_p1;
    end else if (((1'b0 == ap_block_state9) & (ap_predicate_op294_write_state9 == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        acc_context_recovery_TDATA = zext_ln387_fu_1769_p1;
    end else if (((1'b1 == acc_context_recovery_TREADY) & (1'b1 == ap_CS_fsm_state8))) begin
        acc_context_recovery_TDATA = zext_ln414_fu_1675_p1;
    end else begin
        acc_context_recovery_TDATA = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | ((1'b1 == ap_CS_fsm_state16) & (or_ln320_fu_2016_p2 == 1'd0) & (1'd1 == and_ln297_reg_2409)) | ((1'b1 == ap_CS_fsm_state9) & (icmp_ln384_fu_1680_p2 == 1'd0) & (icmp_ln374_reg_2330 == 1'd1)))) begin
        acc_context_recovery_TDATA_blk_n = acc_context_recovery_TREADY;
    end else begin
        acc_context_recovery_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == acc_context_recovery_TREADY) & (1'b1 == ap_CS_fsm_state8)) | (~((1'b1 == ap_block_state16_io) | (1'b1 == ap_block_state16)) & (ap_predicate_op371_write_state16 == 1'b1) & (1'b1 == ap_CS_fsm_state16)) | (~((1'b1 == ap_block_state9_io) | (1'b1 == ap_block_state9)) & (ap_predicate_op294_write_state9 == 1'b1) & (1'b1 == ap_CS_fsm_state9)))) begin
        acc_context_recovery_TVALID = 1'b1;
    end else begin
        acc_context_recovery_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == acc_context_save_TREADY) & (1'b1 == ap_CS_fsm_state15))) begin
        acc_context_save_TDATA = zext_ln358_fu_1996_p1;
    end else if (((1'b0 == ap_block_state14) & (ap_predicate_op337_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        acc_context_save_TDATA = zext_ln362_fu_1905_p1;
    end else if (((1'b0 == ap_block_state1) & (ap_predicate_op193_write_state1 == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_context_save_TDATA = zext_ln314_fu_1407_p1;
    end else begin
        acc_context_save_TDATA = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | ((1'b1 == ap_CS_fsm_state14) & (icmp_ln356_fu_1804_p2 == 1'd1) & (tmp_2_reg_2334 == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'd1 == and_ln310_fu_1315_p2) & (1'd1 == and_ln297_fu_1213_p2) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd1)))) begin
        acc_context_save_TDATA_blk_n = acc_context_save_TREADY;
    end else begin
        acc_context_save_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state14_io) | (1'b1 == ap_block_state14)) & (ap_predicate_op337_write_state14 == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((1'b1 == acc_context_save_TREADY) & (1'b1 == ap_CS_fsm_state15)) | (~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (ap_predicate_op193_write_state1 == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_context_save_TVALID = 1'b1;
    end else begin
        acc_context_save_TVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        addlists_address0 = i_1_fu_318;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        addlists_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        addlists_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        addlists_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        addlists_address0 = 64'd1;
    end else begin
        addlists_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        addlists_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        addlists_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        addlists_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        addlists_address1 = 64'd0;
    end else begin
        addlists_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        addlists_ce0 = 1'b1;
    end else begin
        addlists_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state6) | (~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        addlists_ce1 = 1'b1;
    end else begin
        addlists_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        addlists_d0 = p_cast6_reg_2321;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        addlists_d0 = p_cast4_reg_2311;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        addlists_d0 = p_cast2_reg_2301;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        addlists_d0 = {{context_add_lists_dout[103:64]}};
    end else begin
        addlists_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        addlists_d1 = p_cast5_reg_2316;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        addlists_d1 = p_cast3_reg_2306;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        addlists_d1 = p_cast1_reg_2296;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        addlists_d1 = empty_153_fu_966_p1;
    end else begin
        addlists_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state6) | (~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (tmp_4_nbreadreq_fu_386_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (fsm_state == 4'd5)))) begin
        addlists_we0 = 1'b1;
    end else begin
        addlists_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state6) | (~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (tmp_4_nbreadreq_fu_386_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (fsm_state == 4'd5)))) begin
        addlists_we1 = 1'b1;
    end else begin
        addlists_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state10_io) | (1'b1 == ap_block_state10))) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state14_io) | (1'b1 == ap_block_state14))) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == acc_context_save_TREADY)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state16_io) | (1'b1 == ap_block_state16))) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

always @ (*) begin
    if ((cqe_fifo_full_n == 1'b0)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

always @ (*) begin
    if (((1'b0 == acc_context_data_send_to_datamover_TREADY) | (1'b1 == ap_block_state2))) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((1'b0 == acc_context_recovery_TREADY)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state9_io) | (1'b1 == ap_block_state9))) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (tmp_4_nbreadreq_fu_386_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (fsm_state == 4'd5))) begin
        context_add_lists_blk_n = context_add_lists_empty_n;
    end else begin
        context_add_lists_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (ap_predicate_op105_read_state1 == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        context_add_lists_read = 1'b1;
    end else begin
        context_add_lists_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (fsm_state == 4'd8)))) begin
        cqe_fifo_blk_n = cqe_fifo_full_n;
    end else begin
        cqe_fifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((cqe_fifo_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        cqe_fifo_din = zext_ln472_fu_2238_p1;
    end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1) & (fsm_state == 4'd8))) begin
        cqe_fifo_din = zext_ln466_fu_782_p1;
    end else begin
        cqe_fifo_din = 'bx;
    end
end

always @ (*) begin
    if ((((cqe_fifo_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state19)) | (~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (fsm_state == 4'd8)))) begin
        cqe_fifo_write = 1'b1;
    end else begin
        cqe_fifo_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state9) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd2)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd7)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd3)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd1)))) begin
        ctrl_rsp_from_acc_TDATA_blk_n = ctrl_rsp_from_acc_TVALID;
    end else begin
        ctrl_rsp_from_acc_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state9_io) | (1'b1 == ap_block_state9)) & (1'b1 == ap_CS_fsm_state9)) | (~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (ap_predicate_op148_read_state1 == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | (~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (ap_predicate_op129_read_state1 == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | (~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (ap_predicate_op88_read_state1 == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | (~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (ap_predicate_op60_read_state1 == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | (~((1'b0 == acc_context_data_send_to_datamover_TREADY) | (1'b1 == ap_block_state2)) & (1'b1 == ap_CS_fsm_state2)))) begin
        ctrl_rsp_from_acc_TREADY = 1'b1;
    end else begin
        ctrl_rsp_from_acc_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~(fsm_state == 4'd8) & ~(fsm_state == 4'd6) & ~(fsm_state == 4'd5) & ~(fsm_state == 4'd4) & ~(fsm_state == 4'd9) & ~(fsm_state == 4'd2) & ~(fsm_state == 4'd7) & ~(fsm_state == 4'd3) & ~(fsm_state == 4'd1) & (ap_start == 1'b1) & (tmp_8_nbreadreq_fu_416_p3 == 1'd1) & (tmp_nbreadreq_fu_408_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        opc_fifo_blk_n = opc_fifo_empty_n;
    end else begin
        opc_fifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (ap_predicate_op208_read_state1 == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        opc_fifo_read = 1'b1;
    end else begin
        opc_fifo_read = 1'b0;
    end
end

always @ (*) begin
    if ((~(fsm_state == 4'd8) & ~(fsm_state == 4'd6) & ~(fsm_state == 4'd5) & ~(fsm_state == 4'd4) & ~(fsm_state == 4'd9) & ~(fsm_state == 4'd2) & ~(fsm_state == 4'd7) & ~(fsm_state == 4'd3) & ~(fsm_state == 4'd1) & (ap_start == 1'b1) & (tmp_8_nbreadreq_fu_416_p3 == 1'd1) & (tmp_nbreadreq_fu_408_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        outstanding_num_fifo_blk_n = outstanding_num_fifo_empty_n;
    end else begin
        outstanding_num_fifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (ap_predicate_op210_read_state1 == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        outstanding_num_fifo_read = 1'b1;
    end else begin
        outstanding_num_fifo_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        rsp_data_address0 = add_ln357_fu_1809_p2;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        rsp_data_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        rsp_data_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        rsp_data_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        rsp_data_address0 = 64'd1;
    end else begin
        rsp_data_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        rsp_data_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        rsp_data_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        rsp_data_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        rsp_data_address1 = 64'd0;
    end else begin
        rsp_data_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (~((1'b1 == ap_block_state14_io) | (1'b1 == ap_block_state14)) & (1'b1 == ap_CS_fsm_state14)) | (~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        rsp_data_ce0 = 1'b1;
    end else begin
        rsp_data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        rsp_data_ce1 = 1'b1;
    end else begin
        rsp_data_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        rsp_data_d0 = trunc_ln337_7_reg_2375;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        rsp_data_d0 = trunc_ln337_5_reg_2365;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        rsp_data_d0 = trunc_ln337_3_reg_2355;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        rsp_data_d0 = {{ctrl_rsp_from_acc_TDATA[103:64]}};
    end else begin
        rsp_data_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        rsp_data_d1 = trunc_ln337_6_reg_2370;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        rsp_data_d1 = trunc_ln337_4_reg_2360;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        rsp_data_d1 = trunc_ln337_2_reg_2350;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        rsp_data_d1 = trunc_ln337_8_fu_1070_p1;
    end else begin
        rsp_data_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd3)))) begin
        rsp_data_we0 = 1'b1;
    end else begin
        rsp_data_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd3)))) begin
        rsp_data_we1 = 1'b1;
    end else begin
        rsp_data_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state16) & (or_ln320_fu_2016_p2 == 1'd0) & (1'd1 == and_ln297_reg_2409)) | ((1'b1 == ap_CS_fsm_state9) & (icmp_ln384_fu_1680_p2 == 1'd0) & (icmp_ln374_reg_2330 == 1'd1)))) begin
        tdest_blk_n = tdest_full_n;
    end else begin
        tdest_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state16) & (ap_predicate_op372_write_state16 == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
        tdest_din = rsp_reg_2384;
    end else if (((1'b0 == ap_block_state9) & (ap_predicate_op295_write_state9 == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        tdest_din = ctrl_rsp_from_acc_TID;
    end else begin
        tdest_din = 'bx;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state16_io) | (1'b1 == ap_block_state16)) & (ap_predicate_op372_write_state16 == 1'b1) & (1'b1 == ap_CS_fsm_state16)) | (~((1'b1 == ap_block_state9_io) | (1'b1 == ap_block_state9)) & (ap_predicate_op295_write_state9 == 1'b1) & (1'b1 == ap_CS_fsm_state9)))) begin
        tdest_write = 1'b1;
    end else begin
        tdest_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((fsm_state == 4'd9)) begin
            tempcqe_payload_buffer_address0 = zext_ln471_fu_1434_p1;
        end else if (((grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd2))) begin
            tempcqe_payload_buffer_address0 = zext_ln453_fu_815_p1;
        end else begin
            tempcqe_payload_buffer_address0 = 'bx;
        end
    end else begin
        tempcqe_payload_buffer_address0 = 'bx;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (fsm_state == 4'd9)) | (~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd2)))) begin
        tempcqe_payload_buffer_ce0 = 1'b1;
    end else begin
        tempcqe_payload_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd2))) begin
        tempcqe_payload_buffer_we0 = shl_ln454_fu_852_p2;
    end else begin
        tempcqe_payload_buffer_we0 = 4'd0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd0) & (fsm_state == 4'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd0) & (fsm_state == 4'd3))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd3))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd0) & (fsm_state == 4'd4))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd4))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (tmp_4_nbreadreq_fu_386_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (fsm_state == 4'd5))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (tmp_4_nbreadreq_fu_386_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (fsm_state == 4'd5))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd0) & (fsm_state == 4'd6))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd6))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & ~(fsm_state == 4'd6) & ~(fsm_state == 4'd5) & ~(fsm_state == 4'd4) & ~(fsm_state == 4'd9) & ~(fsm_state == 4'd3) & ~(fsm_state == 4'd1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (fsm_state == 4'd9))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((1'b0 == acc_context_data_send_to_datamover_TREADY) | (1'b1 == ap_block_state2)) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & ((tmp_4_reg_2286 == 1'd0) | ((icmp_ln405_1_fu_1566_p2 == 1'd1) | (icmp_ln405_reg_2459 == 1'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == acc_context_recovery_TREADY) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if ((~((1'b1 == ap_block_state9_io) | (1'b1 == ap_block_state9)) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if ((~((1'b1 == ap_block_state10_io) | (1'b1 == ap_block_state10)) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if ((~((1'b1 == ap_block_state14_io) | (1'b1 == ap_block_state14)) & (1'b1 == ap_CS_fsm_state14) & ((icmp_ln356_fu_1804_p2 == 1'd1) | (tmp_2_reg_2334 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else if ((~((1'b1 == ap_block_state14_io) | (1'b1 == ap_block_state14)) & (1'b1 == ap_CS_fsm_state14) & (icmp_ln356_fu_1804_p2 == 1'd0) & (tmp_2_reg_2334 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((1'b1 == acc_context_save_TREADY) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            if ((~((1'b1 == ap_block_state16_io) | (1'b1 == ap_block_state16)) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state19 : begin
            if (((cqe_fifo_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_context_data_send_to_datamover_TDEST = 'bx;

assign acc_context_data_send_to_datamover_TID = 'bx;

assign acc_context_data_send_to_datamover_TKEEP = 64'd18446744073709551615;

assign acc_context_data_send_to_datamover_TSTRB = 'bx;

assign add_ln293_fu_1189_p2 = ($signed(outstanding_num) + $signed(4'd15));

assign add_ln357_fu_1809_p2 = (i_fu_314 + 64'd1);

assign add_ln370_fu_1048_p2 = ($signed(context_counter) + $signed(16'd65535));

assign add_ln405_1_fu_1571_p2 = (i_1_fu_318 + 64'd1);

assign add_ln405_fu_1552_p2 = (empty_152_reg_2290 + 64'd1);

assign add_ln423_fu_1489_p2 = (context_counter_load_reg_2263 + 16'd1);

assign add_ln459_fu_890_p2 = (query_buffer_num + 2'd1);

assign add_ln471_fu_1422_p2 = (query_buffer_index + 2'd1);

assign and_ln297_fu_1213_p2 = (icmp_ln297_fu_1201_p2 & icmp_ln297_1_fu_1207_p2);

assign and_ln310_fu_1315_p2 = (icmp_ln310_fu_1309_p2 & icmp_ln300_fu_1265_p2);

assign and_ln327_1_fu_2126_p2 = (need_save_loc_0_reg_688 & icmp_ln297_1_reg_2403);

assign and_ln327_2_fu_2131_p2 = (and_ln327_fu_2121_p2 & and_ln327_1_fu_2126_p2);

assign and_ln327_3_fu_2175_p2 = (xor_ln327_fu_2170_p2 & and_ln327_2_reg_2515);

assign and_ln327_4_fu_2154_p2 = (xor_ln327_1_fu_2148_p2 & icmp_ln297_reg_2397);

assign and_ln327_5_fu_2159_p2 = (icmp_ln327_2_fu_2137_p2 & icmp_ln297_1_reg_2403);

assign and_ln327_6_fu_2164_p2 = (and_ln327_5_fu_2159_p2 & and_ln327_4_fu_2154_p2);

assign and_ln327_fu_2121_p2 = (icmp_ln327_1_fu_2115_p2 & icmp_ln297_reg_2397);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | ((outstanding_num_fifo_empty_n == 1'b0) & (ap_predicate_op210_read_state1 == 1'b1)) | ((opc_fifo_empty_n == 1'b0) & (ap_predicate_op208_read_state1 == 1'b1)) | ((ap_predicate_op193_write_state1 == 1'b1) & (1'b0 == acc_context_save_TREADY)) | ((ap_predicate_op148_read_state1 == 1'b1) & (ctrl_rsp_from_acc_TVALID == 1'b0)) | ((ap_predicate_op144_write_state1 == 1'b1) & (1'b0 == acc_context_data_send_to_datamover_TREADY)) | ((ap_predicate_op129_read_state1 == 1'b1) & (ctrl_rsp_from_acc_TVALID == 1'b0)) | ((context_add_lists_empty_n == 1'b0) & (ap_predicate_op105_read_state1 == 1'b1)) | ((ap_predicate_op94_write_state1 == 1'b1) & (1'b0 == acc_context_data_send_to_datamover_TREADY)) | ((cqe_fifo_full_n == 1'b0) & (fsm_state == 4'd8)) | ((ctrl_rsp_from_acc_TVALID == 1'b0) & (ap_predicate_op88_read_state1 == 1'b1)) | ((ctrl_rsp_from_acc_TVALID == 1'b0) & (ap_predicate_op60_read_state1 == 1'b1)));
end

always @ (*) begin
    ap_block_state10 = ((1'b0 == acc_context_data_send_to_datamover_TREADY) & (tmp_3_reg_2326 == 1'd1));
end

always @ (*) begin
    ap_block_state10_io = ((1'b0 == acc_context_data_send_to_datamover_TREADY) & (tmp_3_reg_2326 == 1'd1));
end

always @ (*) begin
    ap_block_state14 = ((ap_predicate_op337_write_state14 == 1'b1) & (1'b0 == acc_context_save_TREADY));
end

always @ (*) begin
    ap_block_state14_io = ((ap_predicate_op337_write_state14 == 1'b1) & (1'b0 == acc_context_save_TREADY));
end

always @ (*) begin
    ap_block_state16 = (((ap_predicate_op371_write_state16 == 1'b1) & (1'b0 == acc_context_recovery_TREADY)) | ((tdest_full_n == 1'b0) & (ap_predicate_op372_write_state16 == 1'b1)));
end

always @ (*) begin
    ap_block_state16_io = ((ap_predicate_op371_write_state16 == 1'b1) & (1'b0 == acc_context_recovery_TREADY));
end

always @ (*) begin
    ap_block_state1_io = (((ap_predicate_op193_write_state1 == 1'b1) & (1'b0 == acc_context_save_TREADY)) | ((ap_predicate_op144_write_state1 == 1'b1) & (1'b0 == acc_context_data_send_to_datamover_TREADY)) | ((ap_predicate_op94_write_state1 == 1'b1) & (1'b0 == acc_context_data_send_to_datamover_TREADY)));
end

always @ (*) begin
    ap_block_state2 = ((ctrl_rsp_from_acc_TVALID == 1'b0) | (1'b0 == acc_context_data_send_to_datamover_TREADY));
end

always @ (*) begin
    ap_block_state9 = ((ctrl_rsp_from_acc_TVALID == 1'b0) | ((tdest_full_n == 1'b0) & (ap_predicate_op295_write_state9 == 1'b1)) | ((ap_predicate_op294_write_state9 == 1'b1) & (1'b0 == acc_context_recovery_TREADY)));
end

always @ (*) begin
    ap_block_state9_io = ((ap_predicate_op294_write_state9 == 1'b1) & (1'b0 == acc_context_recovery_TREADY));
end

always @ (*) begin
    ap_condition_248 = (~(fsm_state == 4'd8) & ~(fsm_state == 4'd6) & ~(fsm_state == 4'd5) & ~(fsm_state == 4'd4) & ~(fsm_state == 4'd9) & ~(fsm_state == 4'd2) & ~(fsm_state == 4'd7) & ~(fsm_state == 4'd3) & ~(fsm_state == 4'd1) & (tmp_8_nbreadreq_fu_416_p3 == 1'd1) & (tmp_nbreadreq_fu_408_p3 == 1'd1));
end

always @ (*) begin
    ap_condition_463 = (~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_condition_485 = (~((1'b1 == ap_block_state9_io) | (1'b1 == ap_block_state9)) & (1'b1 == ap_CS_fsm_state9));
end

always @ (*) begin
    ap_condition_643 = ((trunc_ln1_fu_1151_p4 == 16'd0) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd1));
end

always @ (*) begin
    ap_condition_647 = ((trunc_ln1_fu_1151_p4 == 16'd3) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd1));
end

always @ (*) begin
    ap_condition_651 = (~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1) & (1'd1 == and_ln297_fu_1213_p2) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd1));
end

always @ (*) begin
    ap_predicate_op105_read_state1 = ((tmp_4_nbreadreq_fu_386_p3 == 1'd1) & (fsm_state == 4'd5));
end

always @ (*) begin
    ap_predicate_op129_read_state1 = ((grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd3));
end

always @ (*) begin
    ap_predicate_op144_write_state1 = ((grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd3));
end

always @ (*) begin
    ap_predicate_op148_read_state1 = ((grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd1));
end

always @ (*) begin
    ap_predicate_op193_write_state1 = ((1'd1 == and_ln310_fu_1315_p2) & (1'd1 == and_ln297_fu_1213_p2) & (grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd1));
end

always @ (*) begin
    ap_predicate_op208_read_state1 = (~(fsm_state == 4'd8) & ~(fsm_state == 4'd6) & ~(fsm_state == 4'd5) & ~(fsm_state == 4'd4) & ~(fsm_state == 4'd9) & ~(fsm_state == 4'd2) & ~(fsm_state == 4'd7) & ~(fsm_state == 4'd3) & ~(fsm_state == 4'd1) & (tmp_8_nbreadreq_fu_416_p3 == 1'd1) & (tmp_nbreadreq_fu_408_p3 == 1'd1));
end

always @ (*) begin
    ap_predicate_op210_read_state1 = (~(fsm_state == 4'd8) & ~(fsm_state == 4'd6) & ~(fsm_state == 4'd5) & ~(fsm_state == 4'd4) & ~(fsm_state == 4'd9) & ~(fsm_state == 4'd2) & ~(fsm_state == 4'd7) & ~(fsm_state == 4'd3) & ~(fsm_state == 4'd1) & (tmp_8_nbreadreq_fu_416_p3 == 1'd1) & (tmp_nbreadreq_fu_408_p3 == 1'd1));
end

always @ (*) begin
    ap_predicate_op294_write_state9 = ((icmp_ln384_fu_1680_p2 == 1'd0) & (icmp_ln374_reg_2330 == 1'd1));
end

always @ (*) begin
    ap_predicate_op295_write_state9 = ((icmp_ln384_fu_1680_p2 == 1'd0) & (icmp_ln374_reg_2330 == 1'd1));
end

always @ (*) begin
    ap_predicate_op337_write_state14 = ((icmp_ln356_fu_1804_p2 == 1'd1) & (tmp_2_reg_2334 == 1'd1));
end

always @ (*) begin
    ap_predicate_op371_write_state16 = ((or_ln320_fu_2016_p2 == 1'd0) & (1'd1 == and_ln297_reg_2409));
end

always @ (*) begin
    ap_predicate_op372_write_state16 = ((or_ln320_fu_2016_p2 == 1'd0) & (1'd1 == and_ln297_reg_2409));
end

always @ (*) begin
    ap_predicate_op60_read_state1 = ((grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd2));
end

always @ (*) begin
    ap_predicate_op88_read_state1 = ((grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd7));
end

always @ (*) begin
    ap_predicate_op94_write_state1 = ((grp_nbreadreq_fu_329_p7 == 1'd1) & (fsm_state == 4'd7));
end

assign available_buf_num_1_fu_1066_p1 = ctrl_rsp_from_acc_TDATA[63:0];

assign bf_set1_fu_836_p3 = {{trunc_ln454_fu_832_p1}, {ctrl_rsp_from_acc_TID}};

assign empty_152_fu_962_p1 = context_add_lists_dout[63:0];

assign empty_153_fu_966_p1 = context_add_lists_dout[39:0];

assign grp_fu_702_p2 = ($signed(old_bbt) + $signed(32'd4294967232));

assign grp_nbreadreq_fu_329_p7 = ctrl_rsp_from_acc_TVALID;

assign icmp_ln297_1_fu_1207_p2 = ((trunc_ln1_fu_1151_p4 == 16'd1) ? 1'b1 : 1'b0);

assign icmp_ln297_fu_1201_p2 = ((opc == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln300_fu_1265_p2 = ((trunc_ln5_fu_1255_p4 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln310_fu_1309_p2 = ((trunc_ln4_fu_1239_p4 != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln320_fu_2011_p2 = ((trunc_ln3_reg_2418 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln327_1_fu_2115_p2 = ((old_bbt_loc_0_reg_679 != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln327_2_fu_2137_p2 = ((new_bbt_loc_0_reg_670 != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln327_3_fu_2110_p2 = ((add_ln293_reg_2392 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln327_fu_2105_p2 = ((opc_load_reg_2246 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln356_fu_1804_p2 = ((i_fu_314 == available_buf_num_1_reg_2345) ? 1'b1 : 1'b0);

assign icmp_ln374_fu_1060_p2 = ((add_ln370_fu_1048_p2 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln384_fu_1680_p2 = ((new_bbt_load_reg_2251 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln390_1_fu_762_p2 = ((outstanding_num == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln390_fu_1774_p2 = ((reg_712 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln405_1_fu_1566_p2 = ((i_1_fu_318 == add_ln405_reg_2470) ? 1'b1 : 1'b0);

assign icmp_ln405_fu_1547_p2 = ((empty_152_reg_2290 == 64'd0) ? 1'b1 : 1'b0);

assign icmp_ln427_1_fu_1500_p2 = ((reg_712 == 32'd64) ? 1'b1 : 1'b0);

assign icmp_ln427_fu_1494_p2 = ((add_ln423_fu_1489_p2 == 16'd64) ? 1'b1 : 1'b0);

assign icmp_ln435_fu_1527_p2 = ((old_bbt_loc_1_reg_634 == 32'd64) ? 1'b1 : 1'b0);

assign icmp_ln444_fu_916_p2 = ((new_bbt == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln467_fu_787_p2 = ((opc == 32'd2) ? 1'b1 : 1'b0);

assign mem_req_saddr_1_fu_1321_p2 = (trunc_ln6_fu_1277_p4 | 40'd128);

assign or_ln1_fu_1171_p3 = {{1'd1}, {trunc_ln327_fu_737_p1}};

assign or_ln314_1_fu_1401_p2 = (tmp13_fu_1385_p7 | 72'd2112);

assign or_ln314_fu_1335_p2 = (shl_ln5_fu_1327_p3 | 104'd281479271680064);

assign or_ln320_fu_2016_p2 = (icmp_ln320_fu_2011_p2 | icmp_ln300_reg_2429);

assign or_ln323_1_fu_2094_p2 = (tmp19_fu_2078_p7 | 72'd2240);

assign or_ln323_fu_2028_p2 = (shl_ln6_fu_2021_p3 | 104'd281479271680192);

assign or_ln327_1_fu_2187_p2 = (and_ln327_6_reg_2520 | and_ln327_3_fu_2175_p2);

assign or_ln327_2_fu_2199_p2 = (icmp_ln327_reg_2502 | icmp_ln327_3_reg_2510);

assign or_ln327_3_fu_2211_p2 = (or_ln327_2_fu_2199_p2 | or_ln327_1_fu_2187_p2);

assign or_ln327_fu_2143_p2 = (icmp_ln327_reg_2502 | and_ln327_2_fu_2131_p2);

assign or_ln358_1_fu_1990_p2 = (tmp16_fu_1974_p7 | 72'd4096);

assign or_ln358_fu_1924_p2 = (shl_ln2_fu_1916_p3 | 104'd281479271682048);

assign or_ln362_1_fu_1899_p2 = (tmp11_fu_1883_p7 | 72'd64);

assign or_ln362_fu_1833_p2 = (shl_ln1_fu_1825_p3 | 104'd281479271678016);

assign or_ln387_1_fu_1763_p2 = (tmp21_fu_1747_p7 | 72'd2240);

assign or_ln387_fu_1697_p2 = (shl_ln3_fu_1689_p3 | 104'd281479271680192);

assign or_ln414_1_fu_1669_p2 = (tmp26_fu_1653_p7 | 72'd4096);

assign or_ln414_fu_1603_p2 = (shl_ln4_fu_1595_p3 | 104'd281479271682048);

assign or_ln427_fu_1506_p2 = (icmp_ln427_fu_1494_p2 | icmp_ln427_1_fu_1500_p2);

assign pkt_last_1_fu_1416_p2 = ((query_buffer_index == query_buffer_num) ? 1'b1 : 1'b0);

assign pkt_last_fu_768_p2 = ((opc != 32'd2) ? 1'b1 : 1'b0);

assign query_ops_index_load_load_fu_820_p1 = query_ops_index;

assign select_ln327_1_fu_2192_p3 = ((icmp_ln327_reg_2502[0:0] == 1'b1) ? 4'd2 : 4'd8);

assign select_ln327_2_fu_2203_p3 = ((or_ln327_1_fu_2187_p2[0:0] == 1'b1) ? select_ln327_fu_2180_p3 : select_ln327_1_fu_2192_p3);

assign select_ln327_3_fu_2217_p3 = ((or_ln327_3_fu_2211_p2[0:0] == 1'b1) ? select_ln327_2_fu_2203_p3 : 4'd1);

assign select_ln327_fu_2180_p3 = ((and_ln327_6_reg_2520[0:0] == 1'b1) ? 4'd5 : 4'd3);

assign select_ln390_1_fu_1787_p3 = ((icmp_ln390_fu_1774_p2[0:0] == 1'b1) ? select_ln390_fu_1780_p3 : 4'd6);

assign select_ln390_fu_1780_p3 = ((icmp_ln390_1_reg_2268[0:0] == 1'b1) ? 4'd8 : 4'd1);

assign select_ln416_fu_1582_p3 = ((icmp_ln390_1_reg_2268[0:0] == 1'b1) ? 4'd8 : 4'd1);

assign select_ln427_fu_1513_p3 = ((or_ln427_fu_1506_p2[0:0] == 1'b1) ? 16'd0 : add_ln423_fu_1489_p2);

assign select_ln435_fu_1533_p3 = ((icmp_ln435_fu_1527_p2[0:0] == 1'b1) ? 4'd7 : 4'd6);

assign select_ln444_1_fu_930_p3 = ((icmp_ln444_fu_916_p2[0:0] == 1'b1) ? select_ln444_fu_922_p3 : 4'd5);

assign select_ln444_fu_922_p3 = ((icmp_ln390_1_fu_762_p2[0:0] == 1'b1) ? 4'd8 : 4'd1);

assign select_ln460_fu_902_p3 = ((icmp_ln390_1_fu_762_p2[0:0] == 1'b1) ? 4'd8 : 4'd1);

assign select_ln467_fu_793_p3 = ((icmp_ln467_fu_787_p2[0:0] == 1'b1) ? 4'd9 : 4'd0);

assign select_ln473_fu_1439_p3 = ((pkt_last_1_fu_1416_p2[0:0] == 1'b1) ? 4'd9 : 4'd0);

assign sext_ln290_fu_1179_p1 = $signed(or_ln1_fu_1171_p3);

assign shl_ln1_fu_1825_p3 = {{old_context_address}, {64'd0}};

assign shl_ln2_fu_1916_p3 = {{rsp_data_q0}, {64'd0}};

assign shl_ln3_fu_1689_p3 = {{new_context_address}, {64'd0}};

assign shl_ln454_2_fu_859_p3 = {{query_ops_index}, {4'd0}};

assign shl_ln454_fu_852_p2 = 4'd3 << zext_ln454_1_fu_848_p1;

assign shl_ln4_fu_1595_p3 = {{addlists_q0}, {64'd0}};

assign shl_ln5_fu_1327_p3 = {{mem_req_saddr_1_fu_1321_p2}, {64'd0}};

assign shl_ln6_fu_2021_p3 = {{mem_req_saddr_2_reg_2435}, {64'd0}};

assign shl_ln_fu_824_p3 = {{query_ops_index}, {1'd0}};

assign tempcqe_payload_buffer_d0 = zext_ln454_fu_844_p1 << zext_ln454_2_fu_867_p1;

assign tmp11_fu_1883_p7 = {{{{{{tmp_14_fu_1873_p4}, {tmp_12_fu_1857_p3}}, {tmp_13_fu_1865_p3}}, {tmp_11_fu_1847_p4}}, {tmp_10_fu_1839_p3}}, {23'd0}};

assign tmp13_fu_1385_p7 = {{{{{{tmp_34_fu_1375_p4}, {tmp_32_fu_1359_p3}}, {tmp_33_fu_1367_p3}}, {tmp_31_fu_1349_p4}}, {tmp_30_fu_1341_p3}}, {23'd0}};

assign tmp16_fu_1974_p7 = {{{{{{tmp_19_fu_1964_p4}, {tmp_17_fu_1948_p3}}, {tmp_18_fu_1956_p3}}, {tmp_16_fu_1938_p4}}, {tmp_15_fu_1930_p3}}, {23'd0}};

assign tmp19_fu_2078_p7 = {{{{{{tmp_39_fu_2068_p4}, {tmp_37_fu_2052_p3}}, {tmp_38_fu_2060_p3}}, {tmp_36_fu_2042_p4}}, {tmp_35_fu_2034_p3}}, {23'd0}};

assign tmp21_fu_1747_p7 = {{{{{{tmp_24_fu_1737_p4}, {tmp_22_fu_1721_p3}}, {tmp_23_fu_1729_p3}}, {tmp_21_fu_1711_p4}}, {tmp_20_fu_1703_p3}}, {23'd0}};

assign tmp26_fu_1653_p7 = {{{{{{tmp_29_fu_1643_p4}, {tmp_27_fu_1627_p3}}, {tmp_28_fu_1635_p3}}, {tmp_26_fu_1617_p4}}, {tmp_25_fu_1609_p3}}, {23'd0}};

assign tmp_10_fu_1839_p3 = or_ln362_fu_1833_p2[32'd32];

assign tmp_11_fu_1847_p4 = {{or_ln362_fu_1833_p2[45:40]}};

assign tmp_12_fu_1857_p3 = or_ln362_fu_1833_p2[32'd56];

assign tmp_13_fu_1865_p3 = or_ln362_fu_1833_p2[32'd48];

assign tmp_14_fu_1873_p4 = {{or_ln362_fu_1833_p2[103:64]}};

assign tmp_15_fu_1930_p3 = or_ln358_fu_1924_p2[32'd32];

assign tmp_16_fu_1938_p4 = {{or_ln358_fu_1924_p2[45:40]}};

assign tmp_17_fu_1948_p3 = or_ln358_fu_1924_p2[32'd56];

assign tmp_18_fu_1956_p3 = or_ln358_fu_1924_p2[32'd48];

assign tmp_19_fu_1964_p4 = {{or_ln358_fu_1924_p2[103:64]}};

assign tmp_20_fu_1703_p3 = or_ln387_fu_1697_p2[32'd32];

assign tmp_21_fu_1711_p4 = {{or_ln387_fu_1697_p2[45:40]}};

assign tmp_22_fu_1721_p3 = or_ln387_fu_1697_p2[32'd56];

assign tmp_23_fu_1729_p3 = or_ln387_fu_1697_p2[32'd48];

assign tmp_24_fu_1737_p4 = {{or_ln387_fu_1697_p2[103:64]}};

assign tmp_25_fu_1609_p3 = or_ln414_fu_1603_p2[32'd32];

assign tmp_26_fu_1617_p4 = {{or_ln414_fu_1603_p2[45:40]}};

assign tmp_27_fu_1627_p3 = or_ln414_fu_1603_p2[32'd56];

assign tmp_28_fu_1635_p3 = or_ln414_fu_1603_p2[32'd48];

assign tmp_29_fu_1643_p4 = {{or_ln414_fu_1603_p2[103:64]}};

assign tmp_30_fu_1341_p3 = or_ln314_fu_1335_p2[32'd32];

assign tmp_31_fu_1349_p4 = {{or_ln314_fu_1335_p2[45:40]}};

assign tmp_32_fu_1359_p3 = or_ln314_fu_1335_p2[32'd56];

assign tmp_33_fu_1367_p3 = or_ln314_fu_1335_p2[32'd48];

assign tmp_34_fu_1375_p4 = {{or_ln314_fu_1335_p2[103:64]}};

assign tmp_35_fu_2034_p3 = or_ln323_fu_2028_p2[32'd32];

assign tmp_36_fu_2042_p4 = {{or_ln323_fu_2028_p2[45:40]}};

assign tmp_37_fu_2052_p3 = or_ln323_fu_2028_p2[32'd56];

assign tmp_38_fu_2060_p3 = or_ln323_fu_2028_p2[32'd48];

assign tmp_39_fu_2068_p4 = {{or_ln323_fu_2028_p2[103:64]}};

assign tmp_4_nbreadreq_fu_386_p3 = context_add_lists_empty_n;

assign tmp_8_nbreadreq_fu_416_p3 = outstanding_num_fifo_empty_n;

assign tmp_9_fu_2231_p3 = {{pkt_last_1_reg_2443}, {tempcqe_payload_buffer_q0}};

assign tmp_nbreadreq_fu_408_p3 = opc_fifo_empty_n;

assign tmp_s_fu_774_p3 = {{pkt_last_fu_768_p2}, {zext_ln327_fu_733_p1}};

assign trunc_ln1_fu_1151_p4 = {{ctrl_rsp_from_acc_TDATA[511:496]}};

assign trunc_ln327_1_fu_741_p1 = tempcqe[7:0];

assign trunc_ln327_fu_737_p1 = tempcqe[15:0];

assign trunc_ln337_8_fu_1070_p1 = ctrl_rsp_from_acc_TDATA[39:0];

assign trunc_ln454_fu_832_p1 = ctrl_rsp_from_acc_TDATA[7:0];

assign trunc_ln4_fu_1239_p4 = {{ctrl_rsp_from_acc_TDATA[79:48]}};

assign trunc_ln5_fu_1255_p4 = {{ctrl_rsp_from_acc_TDATA[47:40]}};

assign trunc_ln6_fu_1277_p4 = {{ctrl_rsp_from_acc_TDATA[151:112]}};

assign xor_ln327_1_fu_2148_p2 = (or_ln327_fu_2143_p2 ^ 1'd1);

assign xor_ln327_fu_2170_p2 = (icmp_ln327_reg_2502 ^ 1'd1);

assign xor_ln457_fu_878_p2 = (query_ops_index ^ 1'd1);

assign zext_ln283_cast_fu_1471_p3 = {{9'd256}, {trunc_ln327_1_fu_741_p1}};

assign zext_ln283_fu_1479_p1 = zext_ln283_cast_fu_1471_p3;

assign zext_ln292_fu_1161_p1 = trunc_ln327_fu_737_p1;

assign zext_ln314_fu_1407_p1 = or_ln314_1_fu_1401_p2;

assign zext_ln318_fu_2001_p1 = storemerge_reg_657;

assign zext_ln323_fu_2100_p1 = or_ln323_1_fu_2094_p2;

assign zext_ln327_fu_733_p1 = tempcqe;

assign zext_ln358_fu_1996_p1 = or_ln358_1_fu_1990_p2;

assign zext_ln362_fu_1905_p1 = or_ln362_1_fu_1899_p2;

assign zext_ln387_fu_1769_p1 = or_ln387_1_fu_1763_p2;

assign zext_ln414_fu_1675_p1 = or_ln414_1_fu_1669_p2;

assign zext_ln453_fu_815_p1 = query_buffer_num;

assign zext_ln454_1_fu_848_p1 = shl_ln_fu_824_p3;

assign zext_ln454_2_fu_867_p1 = shl_ln454_2_fu_859_p3;

assign zext_ln454_fu_844_p1 = bf_set1_fu_836_p3;

assign zext_ln466_fu_782_p1 = tmp_s_fu_774_p3;

assign zext_ln471_fu_1434_p1 = query_buffer_index;

assign zext_ln472_fu_2238_p1 = tmp_9_fu_2231_p3;

always @ (posedge ap_clk) begin
    storemerge_reg_657[4:0] <= 5'b00000;
end

endmodule //AssScheduler_CtrlRspHandler
