#pragma once

/* Runtime-programmable fixed-row filter protocol. Keep this header C-only so
 * the host SQL compiler and the HLS operator share the exact wire format. */
#define SELECTIVE_FILTER_V2_MAGIC 0x324c5153U /* "SQL2" little-endian */
#define SELECTIVE_FILTER_V2_VERSION 2U
#define SELECTIVE_FILTER_V2_MAX_PREDICATES 8U
#define SELECTIVE_FILTER_V2_MAX_TOKENS 15U
#define SELECTIVE_FILTER_V2_MAX_RECORD_BYTES 4096U

#define SELECTIVE_FILTER_TYPE_U8 0U
#define SELECTIVE_FILTER_TYPE_U16 1U
#define SELECTIVE_FILTER_TYPE_U32 2U
#define SELECTIVE_FILTER_TYPE_U64 3U
#define SELECTIVE_FILTER_TYPE_I8 4U
#define SELECTIVE_FILTER_TYPE_I16 5U
#define SELECTIVE_FILTER_TYPE_I32 6U
#define SELECTIVE_FILTER_TYPE_I64 7U

#define SELECTIVE_FILTER_CMP_EQ 0U
#define SELECTIVE_FILTER_CMP_NE 1U
#define SELECTIVE_FILTER_CMP_LT 2U
#define SELECTIVE_FILTER_CMP_LE 3U
#define SELECTIVE_FILTER_CMP_GT 4U
#define SELECTIVE_FILTER_CMP_GE 5U

#define SELECTIVE_FILTER_TOKEN_PREDICATE_MAX 7U
#define SELECTIVE_FILTER_TOKEN_AND 0x80U
#define SELECTIVE_FILTER_TOKEN_OR 0x81U
#define SELECTIVE_FILTER_TOKEN_NOT 0x82U

/* Host byte offsets in the 4KB filter context page. The runtime maps host
 * offset zero to HLS context word SELECTIVE_FILTER_STATIC_CONTEXT_BASE. */
#define SELECTIVE_FILTER_V2_HEADER_BYTES 64U
#define SELECTIVE_FILTER_V2_PREDICATE_BYTES 16U
#define SELECTIVE_FILTER_V2_PREDICATES_OFFSET 64U

/* Header u32 fields. */
#define SELECTIVE_FILTER_V2_HDR_RECORD_COUNT 0U
#define SELECTIVE_FILTER_V2_HDR_RECORD_BYTES 4U
#define SELECTIVE_FILTER_V2_HDR_OUTPUT_MODE 20U
#define SELECTIVE_FILTER_V2_HDR_MAGIC 24U
#define SELECTIVE_FILTER_V2_HDR_VERSION 28U
#define SELECTIVE_FILTER_V2_HDR_PREDICATE_COUNT 32U
#define SELECTIVE_FILTER_V2_HDR_TOKEN_COUNT 36U
#define SELECTIVE_FILTER_V2_HDR_PROJECTION_OFFSET 40U
#define SELECTIVE_FILTER_V2_HDR_PROJECTION_TYPE 44U
#define SELECTIVE_FILTER_V2_HDR_TOKENS 48U

/* One predicate descriptor: u32 offset, u8 type, u8 comparison, two reserved
 * bytes, then a little-endian u64 literal. Fields may not cross a 64B beat. */
#define SELECTIVE_FILTER_V2_PRED_OFFSET 0U
#define SELECTIVE_FILTER_V2_PRED_TYPE 4U
#define SELECTIVE_FILTER_V2_PRED_COMPARISON 5U
#define SELECTIVE_FILTER_V2_PRED_LITERAL 8U
