# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2021 - 2022 ICT of CAS.
# Yisong Chang <changyisong@ict.ac.cn>

obj-$(CONFIG_SERVE_ZYNQMP)      += zynqmp.o
obj-$(CONFIG_SERVE_CLK_SLCR)	+= slcr.o
