// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="filter_filter,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu19eg-ffvd1760-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.352000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=675,HLS_SYN_LUT=94,HLS_VERSION=2022_2}" *)

module accExamplePlusOperator (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_in_TDATA,
        data_in_TVALID,
        data_in_TREADY,
        data_in_TKEEP,
        data_in_TSTRB,
        data_in_TUSER,
        data_in_TLAST,
        data_in_TID,
        data_in_TDEST,
        context_r_Addr_A,
        context_r_EN_A,
        context_r_WEN_A,
        context_r_Din_A,
        context_r_Dout_A,
        context_r_Clk_A,
        context_r_Rst_A,
        data_out_TDATA,
        data_out_TVALID,
        data_out_TREADY,
        data_out_TKEEP,
        data_out_TSTRB,
        data_out_TUSER,
        data_out_TLAST,
        data_out_TID,
        data_out_TDEST,
        operator_done_signal_TDATA,
        operator_done_signal_TVALID,
        operator_done_signal_TREADY
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [511:0] data_in_TDATA;
input   data_in_TVALID;
output   data_in_TREADY;
input  [63:0] data_in_TKEEP;
input  [63:0] data_in_TSTRB;
input  [7:0] data_in_TUSER;
input  [0:0] data_in_TLAST;
input  [7:0] data_in_TID;
input  [7:0] data_in_TDEST;
output  [31:0] context_r_Addr_A;
output   context_r_EN_A;
output  [63:0] context_r_WEN_A;
output  [511:0] context_r_Din_A;
input  [511:0] context_r_Dout_A;
output   context_r_Clk_A;
output   context_r_Rst_A;
output  [511:0] data_out_TDATA;
output   data_out_TVALID;
input   data_out_TREADY;
output  [63:0] data_out_TKEEP;
output  [63:0] data_out_TSTRB;
output  [7:0] data_out_TUSER;
output  [0:0] data_out_TLAST;
output  [7:0] data_out_TID;
output  [7:0] data_out_TDEST;
output  [7:0] operator_done_signal_TDATA;
output   operator_done_signal_TVALID;
input   operator_done_signal_TREADY;

assign operator_done_signal_TVALID = 0;
assign operator_done_signal_TDATA = 0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg context_r_EN_A;
reg[63:0] context_r_WEN_A;
reg context_r_Rst_A;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_ap_start;
wire    grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_ap_done;
wire    grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_ap_idle;
wire    grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_ap_ready;
wire    grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TREADY;
wire    grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_in_TREADY;
wire   [511:0] grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TDATA;
wire    grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TVALID;
wire   [63:0] grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TKEEP;
wire   [63:0] grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TSTRB;
wire   [7:0] grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TUSER;
wire   [0:0] grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TLAST;
wire   [7:0] grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TID;
wire   [7:0] grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TDEST;
reg    grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire   [31:0] context_r_addr_gep_fu_76_p3;
wire    ap_CS_fsm_state4;
wire    regslice_both_data_out_V_data_V_U_apdone_blk;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    regslice_both_data_in_V_data_V_U_apdone_blk;
wire   [511:0] data_in_TDATA_int_regslice;
wire    data_in_TVALID_int_regslice;
reg    data_in_TREADY_int_regslice;
wire    regslice_both_data_in_V_data_V_U_ack_in;
wire    regslice_both_data_in_V_keep_V_U_apdone_blk;
wire   [63:0] data_in_TKEEP_int_regslice;
wire    regslice_both_data_in_V_keep_V_U_vld_out;
wire    regslice_both_data_in_V_keep_V_U_ack_in;
wire    regslice_both_data_in_V_strb_V_U_apdone_blk;
wire   [63:0] data_in_TSTRB_int_regslice;
wire    regslice_both_data_in_V_strb_V_U_vld_out;
wire    regslice_both_data_in_V_strb_V_U_ack_in;
wire    regslice_both_data_in_V_user_V_U_apdone_blk;
wire   [7:0] data_in_TUSER_int_regslice;
wire    regslice_both_data_in_V_user_V_U_vld_out;
wire    regslice_both_data_in_V_user_V_U_ack_in;
wire    regslice_both_data_in_V_last_V_U_apdone_blk;
wire   [0:0] data_in_TLAST_int_regslice;
wire    regslice_both_data_in_V_last_V_U_vld_out;
wire    regslice_both_data_in_V_last_V_U_ack_in;
wire    regslice_both_data_in_V_id_V_U_apdone_blk;
wire   [7:0] data_in_TID_int_regslice;
wire    regslice_both_data_in_V_id_V_U_vld_out;
wire    regslice_both_data_in_V_id_V_U_ack_in;
wire    regslice_both_data_in_V_dest_V_U_apdone_blk;
wire   [7:0] data_in_TDEST_int_regslice;
wire    regslice_both_data_in_V_dest_V_U_vld_out;
wire    regslice_both_data_in_V_dest_V_U_ack_in;
wire    data_out_TVALID_int_regslice;
wire    data_out_TREADY_int_regslice;
wire    regslice_both_data_out_V_data_V_U_vld_out;
wire    regslice_both_data_out_V_keep_V_U_apdone_blk;
wire    regslice_both_data_out_V_keep_V_U_ack_in_dummy;
wire    regslice_both_data_out_V_keep_V_U_vld_out;
wire    regslice_both_data_out_V_strb_V_U_apdone_blk;
wire    regslice_both_data_out_V_strb_V_U_ack_in_dummy;
wire    regslice_both_data_out_V_strb_V_U_vld_out;
wire    regslice_both_data_out_V_user_V_U_apdone_blk;
wire    regslice_both_data_out_V_user_V_U_ack_in_dummy;
wire    regslice_both_data_out_V_user_V_U_vld_out;
wire    regslice_both_data_out_V_last_V_U_apdone_blk;
wire    regslice_both_data_out_V_last_V_U_ack_in_dummy;
wire    regslice_both_data_out_V_last_V_U_vld_out;
wire    regslice_both_data_out_V_id_V_U_apdone_blk;
wire    regslice_both_data_out_V_id_V_U_ack_in_dummy;
wire    regslice_both_data_out_V_id_V_U_vld_out;
wire    regslice_both_data_out_V_dest_V_U_apdone_blk;
wire    regslice_both_data_out_V_dest_V_U_ack_in_dummy;
wire    regslice_both_data_out_V_dest_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_ap_start_reg = 1'b0;
end

filter_filter_Pipeline_VITIS_LOOP_34_1 grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_ap_start),
    .ap_done(grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_ap_done),
    .ap_idle(grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_ap_idle),
    .ap_ready(grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_ap_ready),
    .data_in_TVALID(data_in_TVALID_int_regslice),
    .data_out_TREADY(grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TREADY),
    .data_in_TDATA(data_in_TDATA_int_regslice),
    .data_in_TREADY(grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_in_TREADY),
    .data_in_TKEEP(data_in_TKEEP_int_regslice),
    .data_in_TSTRB(data_in_TSTRB_int_regslice),
    .data_in_TUSER(data_in_TUSER_int_regslice),
    .data_in_TLAST(data_in_TLAST_int_regslice),
    .data_in_TID(data_in_TID_int_regslice),
    .data_in_TDEST(data_in_TDEST_int_regslice),
    .data_out_TDATA(grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TDATA),
    .data_out_TVALID(grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TVALID),
    .data_out_TKEEP(grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TKEEP),
    .data_out_TSTRB(grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TSTRB),
    .data_out_TUSER(grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TUSER),
    .data_out_TLAST(grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TLAST),
    .data_out_TID(grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TID),
    .data_out_TDEST(grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TDEST)
);

filter_regslice_both #(
    .DataWidth( 512 ))
regslice_both_data_in_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(data_in_TDATA),
    .vld_in(data_in_TVALID),
    .ack_in(regslice_both_data_in_V_data_V_U_ack_in),
    .data_out(data_in_TDATA_int_regslice),
    .vld_out(data_in_TVALID_int_regslice),
    .ack_out(data_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_data_in_V_data_V_U_apdone_blk)
);

filter_regslice_both #(
    .DataWidth( 64 ))
regslice_both_data_in_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(data_in_TKEEP),
    .vld_in(data_in_TVALID),
    .ack_in(regslice_both_data_in_V_keep_V_U_ack_in),
    .data_out(data_in_TKEEP_int_regslice),
    .vld_out(regslice_both_data_in_V_keep_V_U_vld_out),
    .ack_out(data_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_data_in_V_keep_V_U_apdone_blk)
);

filter_regslice_both #(
    .DataWidth( 64 ))
regslice_both_data_in_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(data_in_TSTRB),
    .vld_in(data_in_TVALID),
    .ack_in(regslice_both_data_in_V_strb_V_U_ack_in),
    .data_out(data_in_TSTRB_int_regslice),
    .vld_out(regslice_both_data_in_V_strb_V_U_vld_out),
    .ack_out(data_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_data_in_V_strb_V_U_apdone_blk)
);

filter_regslice_both #(
    .DataWidth( 8 ))
regslice_both_data_in_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(data_in_TUSER),
    .vld_in(data_in_TVALID),
    .ack_in(regslice_both_data_in_V_user_V_U_ack_in),
    .data_out(data_in_TUSER_int_regslice),
    .vld_out(regslice_both_data_in_V_user_V_U_vld_out),
    .ack_out(data_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_data_in_V_user_V_U_apdone_blk)
);

filter_regslice_both #(
    .DataWidth( 1 ))
regslice_both_data_in_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(data_in_TLAST),
    .vld_in(data_in_TVALID),
    .ack_in(regslice_both_data_in_V_last_V_U_ack_in),
    .data_out(data_in_TLAST_int_regslice),
    .vld_out(regslice_both_data_in_V_last_V_U_vld_out),
    .ack_out(data_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_data_in_V_last_V_U_apdone_blk)
);

filter_regslice_both #(
    .DataWidth( 8 ))
regslice_both_data_in_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(data_in_TID),
    .vld_in(data_in_TVALID),
    .ack_in(regslice_both_data_in_V_id_V_U_ack_in),
    .data_out(data_in_TID_int_regslice),
    .vld_out(regslice_both_data_in_V_id_V_U_vld_out),
    .ack_out(data_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_data_in_V_id_V_U_apdone_blk)
);

filter_regslice_both #(
    .DataWidth( 8 ))
regslice_both_data_in_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(data_in_TDEST),
    .vld_in(data_in_TVALID),
    .ack_in(regslice_both_data_in_V_dest_V_U_ack_in),
    .data_out(data_in_TDEST_int_regslice),
    .vld_out(regslice_both_data_in_V_dest_V_U_vld_out),
    .ack_out(data_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_data_in_V_dest_V_U_apdone_blk)
);

filter_regslice_both #(
    .DataWidth( 512 ))
regslice_both_data_out_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TDATA),
    .vld_in(grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TVALID),
    .ack_in(data_out_TREADY_int_regslice),
    .data_out(data_out_TDATA),
    .vld_out(regslice_both_data_out_V_data_V_U_vld_out),
    .ack_out(data_out_TREADY),
    .apdone_blk(regslice_both_data_out_V_data_V_U_apdone_blk)
);

filter_regslice_both #(
    .DataWidth( 64 ))
regslice_both_data_out_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TKEEP),
    .vld_in(grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TVALID),
    .ack_in(regslice_both_data_out_V_keep_V_U_ack_in_dummy),
    .data_out(data_out_TKEEP),
    .vld_out(regslice_both_data_out_V_keep_V_U_vld_out),
    .ack_out(data_out_TREADY),
    .apdone_blk(regslice_both_data_out_V_keep_V_U_apdone_blk)
);

filter_regslice_both #(
    .DataWidth( 64 ))
regslice_both_data_out_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TSTRB),
    .vld_in(grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TVALID),
    .ack_in(regslice_both_data_out_V_strb_V_U_ack_in_dummy),
    .data_out(data_out_TSTRB),
    .vld_out(regslice_both_data_out_V_strb_V_U_vld_out),
    .ack_out(data_out_TREADY),
    .apdone_blk(regslice_both_data_out_V_strb_V_U_apdone_blk)
);

filter_regslice_both #(
    .DataWidth( 8 ))
regslice_both_data_out_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TUSER),
    .vld_in(grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TVALID),
    .ack_in(regslice_both_data_out_V_user_V_U_ack_in_dummy),
    .data_out(data_out_TUSER),
    .vld_out(regslice_both_data_out_V_user_V_U_vld_out),
    .ack_out(data_out_TREADY),
    .apdone_blk(regslice_both_data_out_V_user_V_U_apdone_blk)
);

filter_regslice_both #(
    .DataWidth( 1 ))
regslice_both_data_out_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TLAST),
    .vld_in(grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TVALID),
    .ack_in(regslice_both_data_out_V_last_V_U_ack_in_dummy),
    .data_out(data_out_TLAST),
    .vld_out(regslice_both_data_out_V_last_V_U_vld_out),
    .ack_out(data_out_TREADY),
    .apdone_blk(regslice_both_data_out_V_last_V_U_apdone_blk)
);

filter_regslice_both #(
    .DataWidth( 8 ))
regslice_both_data_out_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TID),
    .vld_in(grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TVALID),
    .ack_in(regslice_both_data_out_V_id_V_U_ack_in_dummy),
    .data_out(data_out_TID),
    .vld_out(regslice_both_data_out_V_id_V_U_vld_out),
    .ack_out(data_out_TREADY),
    .apdone_blk(regslice_both_data_out_V_id_V_U_apdone_blk)
);

filter_regslice_both #(
    .DataWidth( 8 ))
regslice_both_data_out_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TDEST),
    .vld_in(grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TVALID),
    .ack_in(regslice_both_data_out_V_dest_V_U_ack_in_dummy),
    .data_out(data_out_TDEST),
    .vld_out(regslice_both_data_out_V_dest_V_U_vld_out),
    .ack_out(data_out_TREADY),
    .apdone_blk(regslice_both_data_out_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_ap_start_reg <= 1'b1;
        end else if ((grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_ap_ready == 1'b1)) begin
            grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_data_out_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_data_out_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_data_out_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_data_out_V_data_V_U_apdone_blk == 1'b0))) begin
        context_r_EN_A = 1'b1;
    end else begin
        context_r_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_data_out_V_data_V_U_apdone_blk == 1'b0))) begin
        context_r_WEN_A = 64'd18446744073709551615;
    end else begin
        context_r_WEN_A = 64'd0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        data_in_TREADY_int_regslice = grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_in_TREADY;
    end else begin
        data_in_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_data_out_V_data_V_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign context_r_Addr_A = context_r_addr_gep_fu_76_p3 << 32'd6;

assign context_r_Clk_A = ap_clk;

assign context_r_Din_A = 512'd4294967295;

always @ (*) begin
    context_r_Rst_A = ~ap_rst_n;
end

assign context_r_addr_gep_fu_76_p3 = 64'd3;

assign data_in_TREADY = regslice_both_data_in_V_data_V_U_ack_in;

assign data_out_TVALID = regslice_both_data_out_V_data_V_U_vld_out;

assign data_out_TVALID_int_regslice = grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TVALID;

assign grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_ap_start = grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_ap_start_reg;

assign grp_filter_Pipeline_VITIS_LOOP_34_1_fu_91_data_out_TREADY = (data_out_TREADY_int_regslice & ap_CS_fsm_state3);

endmodule //filter
