// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module lwe_decrypt_write_clear_byte (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_out_TDATA,
        data_out_TVALID,
        data_out_TREADY,
        data_out_TKEEP,
        data_out_TSTRB,
        data_out_TUSER,
        data_out_TLAST,
        data_out_TID,
        data_out_TDEST,
        packet_data_V_read,
        packet_byte_count_V_read,
        clear_u8,
        ap_return_0,
        ap_return_1
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [511:0] data_out_TDATA;
output   data_out_TVALID;
input   data_out_TREADY;
output  [63:0] data_out_TKEEP;
output  [63:0] data_out_TSTRB;
output  [7:0] data_out_TUSER;
output  [0:0] data_out_TLAST;
output  [7:0] data_out_TID;
output  [7:0] data_out_TDEST;
input  [511:0] packet_data_V_read;
input  [6:0] packet_byte_count_V_read;
input  [7:0] clear_u8;
output  [511:0] ap_return_0;
output  [6:0] ap_return_1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[511:0] ap_return_0;
reg[6:0] ap_return_1;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [9:0] shl_ln_fu_116_p3;
reg   [9:0] shl_ln_reg_280;
wire   [9:0] or_ln97_fu_124_p2;
reg   [9:0] or_ln97_reg_288;
wire   [0:0] icmp_ln414_fu_130_p2;
reg   [0:0] icmp_ln414_reg_294;
wire   [511:0] p_Result_s_fu_238_p2;
reg   [511:0] p_Result_s_reg_302;
wire    ap_CS_fsm_state2;
wire   [6:0] add_ln691_fu_244_p2;
wire   [0:0] icmp_ln870_fu_249_p2;
reg   [0:0] icmp_ln870_reg_314;
reg   [511:0] packet_data_ret_reg_318;
wire    ap_CS_fsm_state4;
reg   [6:0] packet_byte_count_ret_reg_323;
wire    grp_flush_clear_packet_fu_92_ap_start;
wire    grp_flush_clear_packet_fu_92_ap_done;
wire    grp_flush_clear_packet_fu_92_ap_idle;
wire    grp_flush_clear_packet_fu_92_ap_ready;
wire   [511:0] grp_flush_clear_packet_fu_92_data_out_TDATA;
wire    grp_flush_clear_packet_fu_92_data_out_TVALID;
wire    grp_flush_clear_packet_fu_92_data_out_TREADY;
wire   [63:0] grp_flush_clear_packet_fu_92_data_out_TKEEP;
wire   [63:0] grp_flush_clear_packet_fu_92_data_out_TSTRB;
wire   [7:0] grp_flush_clear_packet_fu_92_data_out_TUSER;
wire   [0:0] grp_flush_clear_packet_fu_92_data_out_TLAST;
wire   [7:0] grp_flush_clear_packet_fu_92_data_out_TID;
wire   [7:0] grp_flush_clear_packet_fu_92_data_out_TDEST;
wire   [511:0] grp_flush_clear_packet_fu_92_ap_return_0;
wire   [6:0] grp_flush_clear_packet_fu_92_ap_return_1;
reg   [511:0] ap_phi_mux_packet_data_0_phi_fu_77_p4;
reg   [511:0] packet_data_0_reg_74;
wire    ap_CS_fsm_state5;
reg   [6:0] ap_phi_mux_packet_byte_count_0_phi_fu_86_p4;
reg   [6:0] packet_byte_count_0_reg_83;
reg    grp_flush_clear_packet_fu_92_ap_start_reg;
wire    ap_CS_fsm_state3;
wire   [9:0] sub_ln414_fu_140_p2;
wire   [9:0] select_ln414_fu_145_p3;
wire   [9:0] select_ln414_2_fu_155_p3;
wire   [9:0] select_ln414_1_fu_150_p3;
wire   [9:0] sub_ln414_1_fu_161_p2;
wire   [511:0] zext_ln215_fu_136_p1;
wire   [511:0] zext_ln414_fu_167_p1;
wire   [511:0] shl_ln414_fu_179_p2;
reg   [511:0] tmp_fu_185_p4;
wire   [511:0] zext_ln414_1_fu_171_p1;
wire   [511:0] zext_ln414_2_fu_175_p1;
wire   [511:0] shl_ln414_1_fu_202_p2;
wire   [511:0] lshr_ln414_fu_208_p2;
wire   [511:0] and_ln414_fu_214_p2;
wire   [511:0] xor_ln414_fu_220_p2;
wire   [511:0] select_ln414_3_fu_195_p3;
wire   [511:0] and_ln414_1_fu_226_p2;
wire   [511:0] and_ln414_2_fu_232_p2;
reg   [511:0] ap_return_0_preg;
reg   [6:0] ap_return_1_preg;
reg   [4:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 shl_ln_reg_280 = 10'd0;
#0 or_ln97_reg_288 = 10'd0;
#0 icmp_ln414_reg_294 = 1'd0;
#0 p_Result_s_reg_302 = 512'd0;
#0 icmp_ln870_reg_314 = 1'd0;
#0 packet_data_ret_reg_318 = 512'd0;
#0 packet_byte_count_ret_reg_323 = 7'd0;
#0 packet_data_0_reg_74 = 512'd0;
#0 packet_byte_count_0_reg_83 = 7'd0;
#0 grp_flush_clear_packet_fu_92_ap_start_reg = 1'b0;
#0 ap_return_0_preg = 512'd0;
#0 ap_return_1_preg = 7'd0;
end

lwe_decrypt_flush_clear_packet grp_flush_clear_packet_fu_92(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_flush_clear_packet_fu_92_ap_start),
    .ap_done(grp_flush_clear_packet_fu_92_ap_done),
    .ap_idle(grp_flush_clear_packet_fu_92_ap_idle),
    .ap_ready(grp_flush_clear_packet_fu_92_ap_ready),
    .data_out_TDATA(grp_flush_clear_packet_fu_92_data_out_TDATA),
    .data_out_TVALID(grp_flush_clear_packet_fu_92_data_out_TVALID),
    .data_out_TREADY(grp_flush_clear_packet_fu_92_data_out_TREADY),
    .data_out_TKEEP(grp_flush_clear_packet_fu_92_data_out_TKEEP),
    .data_out_TSTRB(grp_flush_clear_packet_fu_92_data_out_TSTRB),
    .data_out_TUSER(grp_flush_clear_packet_fu_92_data_out_TUSER),
    .data_out_TLAST(grp_flush_clear_packet_fu_92_data_out_TLAST),
    .data_out_TID(grp_flush_clear_packet_fu_92_data_out_TID),
    .data_out_TDEST(grp_flush_clear_packet_fu_92_data_out_TDEST),
    .packet_data_V_read_6(p_Result_s_reg_302),
    .packet_data_V_read(p_Result_s_reg_302),
    .packet_byte_count_V_read_6(7'd64),
    .packet_byte_count_V_read(7'd64),
    .ap_return_0(grp_flush_clear_packet_fu_92_ap_return_0),
    .ap_return_1(grp_flush_clear_packet_fu_92_ap_return_1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 512'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            ap_return_0_preg <= ap_phi_mux_packet_data_0_phi_fu_77_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 7'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            ap_return_1_preg <= ap_phi_mux_packet_byte_count_0_phi_fu_86_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_flush_clear_packet_fu_92_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_flush_clear_packet_fu_92_ap_start_reg <= 1'b1;
        end else if ((grp_flush_clear_packet_fu_92_ap_ready == 1'b1)) begin
            grp_flush_clear_packet_fu_92_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln414_reg_294 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            icmp_ln414_reg_294 <= icmp_ln414_fu_130_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln870_reg_314 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            icmp_ln870_reg_314 <= icmp_ln870_fu_249_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                or_ln97_reg_288[3] <= 1'b0;
        or_ln97_reg_288[4] <= 1'b0;
        or_ln97_reg_288[5] <= 1'b0;
        or_ln97_reg_288[6] <= 1'b0;
        or_ln97_reg_288[7] <= 1'b0;
        or_ln97_reg_288[8] <= 1'b0;
        or_ln97_reg_288[9] <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
                        or_ln97_reg_288[9 : 3] <= or_ln97_fu_124_p2[9 : 3];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        p_Result_s_reg_302 <= 512'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            p_Result_s_reg_302 <= p_Result_s_fu_238_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        packet_byte_count_0_reg_83 <= 7'd0;
    end else begin
        if (((icmp_ln870_fu_249_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            packet_byte_count_0_reg_83 <= add_ln691_fu_244_p2;
        end else if (((icmp_ln870_reg_314 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
            packet_byte_count_0_reg_83 <= packet_byte_count_ret_reg_323;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        packet_byte_count_ret_reg_323 <= 7'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            packet_byte_count_ret_reg_323 <= grp_flush_clear_packet_fu_92_ap_return_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        packet_data_0_reg_74 <= 512'd0;
    end else begin
        if (((icmp_ln870_fu_249_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            packet_data_0_reg_74 <= p_Result_s_fu_238_p2;
        end else if (((icmp_ln870_reg_314 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
            packet_data_0_reg_74 <= packet_data_ret_reg_318;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        packet_data_ret_reg_318 <= 512'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            packet_data_ret_reg_318 <= grp_flush_clear_packet_fu_92_ap_return_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                shl_ln_reg_280[3] <= 1'b0;
        shl_ln_reg_280[4] <= 1'b0;
        shl_ln_reg_280[5] <= 1'b0;
        shl_ln_reg_280[6] <= 1'b0;
        shl_ln_reg_280[7] <= 1'b0;
        shl_ln_reg_280[8] <= 1'b0;
        shl_ln_reg_280[9] <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
                        shl_ln_reg_280[9 : 3] <= shl_ln_fu_116_p3[9 : 3];
        end
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln870_reg_314 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_phi_mux_packet_byte_count_0_phi_fu_86_p4 = packet_byte_count_ret_reg_323;
    end else begin
        ap_phi_mux_packet_byte_count_0_phi_fu_86_p4 = packet_byte_count_0_reg_83;
    end
end

always @ (*) begin
    if (((icmp_ln870_reg_314 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_phi_mux_packet_data_0_phi_fu_77_p4 = packet_data_ret_reg_318;
    end else begin
        ap_phi_mux_packet_data_0_phi_fu_77_p4 = packet_data_0_reg_74;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_return_0 = ap_phi_mux_packet_data_0_phi_fu_77_p4;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_return_1 = ap_phi_mux_packet_byte_count_0_phi_fu_86_p4;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln870_fu_249_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_flush_clear_packet_fu_92_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln691_fu_244_p2 = (packet_byte_count_V_read + 7'd1);

assign and_ln414_1_fu_226_p2 = (xor_ln414_fu_220_p2 & packet_data_V_read);

assign and_ln414_2_fu_232_p2 = (select_ln414_3_fu_195_p3 & and_ln414_fu_214_p2);

assign and_ln414_fu_214_p2 = (shl_ln414_1_fu_202_p2 & lshr_ln414_fu_208_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign data_out_TDATA = grp_flush_clear_packet_fu_92_data_out_TDATA;

assign data_out_TDEST = grp_flush_clear_packet_fu_92_data_out_TDEST;

assign data_out_TID = grp_flush_clear_packet_fu_92_data_out_TID;

assign data_out_TKEEP = grp_flush_clear_packet_fu_92_data_out_TKEEP;

assign data_out_TLAST = grp_flush_clear_packet_fu_92_data_out_TLAST;

assign data_out_TSTRB = grp_flush_clear_packet_fu_92_data_out_TSTRB;

assign data_out_TUSER = grp_flush_clear_packet_fu_92_data_out_TUSER;

assign data_out_TVALID = grp_flush_clear_packet_fu_92_data_out_TVALID;

assign grp_flush_clear_packet_fu_92_ap_start = grp_flush_clear_packet_fu_92_ap_start_reg;

assign grp_flush_clear_packet_fu_92_data_out_TREADY = (data_out_TREADY & ap_CS_fsm_state4);

assign icmp_ln414_fu_130_p2 = ((shl_ln_fu_116_p3 > or_ln97_fu_124_p2) ? 1'b1 : 1'b0);

assign icmp_ln870_fu_249_p2 = ((add_ln691_fu_244_p2 == 7'd64) ? 1'b1 : 1'b0);

assign lshr_ln414_fu_208_p2 = 512'd13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084095 >> zext_ln414_2_fu_175_p1;

assign or_ln97_fu_124_p2 = (shl_ln_fu_116_p3 | 10'd7);

assign p_Result_s_fu_238_p2 = (and_ln414_2_fu_232_p2 | and_ln414_1_fu_226_p2);

assign select_ln414_1_fu_150_p3 = ((icmp_ln414_reg_294[0:0] == 1'b1) ? or_ln97_reg_288 : shl_ln_reg_280);

assign select_ln414_2_fu_155_p3 = ((icmp_ln414_reg_294[0:0] == 1'b1) ? sub_ln414_fu_140_p2 : shl_ln_reg_280);

assign select_ln414_3_fu_195_p3 = ((icmp_ln414_reg_294[0:0] == 1'b1) ? tmp_fu_185_p4 : shl_ln414_fu_179_p2);

assign select_ln414_fu_145_p3 = ((icmp_ln414_reg_294[0:0] == 1'b1) ? shl_ln_reg_280 : or_ln97_reg_288);

assign shl_ln414_1_fu_202_p2 = 512'd13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084095 << zext_ln414_1_fu_171_p1;

assign shl_ln414_fu_179_p2 = zext_ln215_fu_136_p1 << zext_ln414_fu_167_p1;

assign shl_ln_fu_116_p3 = {{packet_byte_count_V_read}, {3'd0}};

assign sub_ln414_1_fu_161_p2 = (10'd511 - select_ln414_fu_145_p3);

assign sub_ln414_fu_140_p2 = (10'd511 - shl_ln_reg_280);

integer ap_tvar_int_0;

always @ (shl_ln414_fu_179_p2) begin
    for (ap_tvar_int_0 = 512 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 511 - 0) begin
            tmp_fu_185_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            tmp_fu_185_p4[ap_tvar_int_0] = shl_ln414_fu_179_p2[511 - ap_tvar_int_0];
        end
    end
end

assign xor_ln414_fu_220_p2 = (512'd13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084095 ^ and_ln414_fu_214_p2);

assign zext_ln215_fu_136_p1 = clear_u8;

assign zext_ln414_1_fu_171_p1 = select_ln414_1_fu_150_p3;

assign zext_ln414_2_fu_175_p1 = sub_ln414_1_fu_161_p2;

assign zext_ln414_fu_167_p1 = select_ln414_2_fu_155_p3;

always @ (posedge ap_clk) begin
    shl_ln_reg_280[2:0] <= 3'b000;
    or_ln97_reg_288[2:0] <= 3'b111;
end

endmodule //lwe_decrypt_write_clear_byte
