// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module lwe_decrypt_reduce_mask_beats (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        terms_dout,
        terms_empty_n,
        terms_read,
        sums_din,
        sums_full_n,
        sums_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state5 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [639:0] terms_dout;
input   terms_empty_n;
output   terms_read;
output  [255:0] sums_din;
input   sums_full_n;
output   sums_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg terms_read;
reg sums_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    terms_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    sums_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [639:0] terms_read_reg_649;
reg    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
reg   [63:0] tmp_1_reg_655;
reg   [63:0] tmp_2_reg_661;
reg   [63:0] tmp_3_reg_667;
reg   [63:0] tmp_4_reg_673;
reg   [63:0] tmp_5_reg_679;
reg   [63:0] tmp_6_reg_685;
reg   [63:0] tmp_7_reg_691;
wire   [3:0] trunc_ln_fu_199_p4;
reg   [3:0] trunc_ln_reg_697;
wire   [0:0] token_has_body_V_fu_209_p3;
reg   [0:0] token_has_body_V_reg_709;
reg   [0:0] token_has_body_V_reg_709_pp0_iter1_reg;
wire   [0:0] token_end_V_fu_217_p3;
reg   [0:0] token_end_V_reg_721;
reg   [0:0] token_end_V_reg_721_pp0_iter1_reg;
wire   [0:0] cmp_i_fu_225_p2;
reg   [0:0] cmp_i_reg_726;
wire   [0:0] icmp_ln878_fu_231_p2;
reg   [0:0] icmp_ln878_reg_738;
wire   [0:0] icmp_ln878_1_fu_247_p2;
reg   [0:0] icmp_ln878_1_reg_743;
wire   [0:0] icmp_ln886_fu_253_p2;
reg   [0:0] icmp_ln886_reg_748;
wire   [0:0] icmp_ln886_1_fu_269_p2;
reg   [0:0] icmp_ln886_1_reg_753;
wire   [0:0] icmp_ln878_3_fu_285_p2;
reg   [0:0] icmp_ln878_3_reg_758;
wire   [0:0] icmp_ln886_3_fu_301_p2;
reg   [0:0] icmp_ln886_3_reg_763;
reg   [63:0] tmp_8_reg_768;
reg   [63:0] tmp_8_reg_768_pp0_iter1_reg;
reg   [3:0] tmp_9_reg_773;
reg   [3:0] tmp_9_reg_773_pp0_iter1_reg;
wire   [63:0] token_before_V_fu_588_p2;
reg   [63:0] token_before_V_reg_778;
wire   [63:0] token_after_V_fu_624_p2;
reg   [63:0] token_after_V_reg_783;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_flush_enable;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_pp0_stage0_01001;
wire   [2:0] tmp_41_fu_237_p4;
wire   [2:0] tmp_42_fu_259_p4;
wire   [1:0] tmp_43_fu_275_p4;
wire   [1:0] tmp_44_fu_291_p4;
wire   [0:0] or_ln452_fu_330_p2;
wire   [63:0] tmp_fu_327_p1;
wire   [0:0] or_ln452_1_fu_342_p2;
wire   [0:0] and_ln454_fu_353_p2;
wire   [0:0] icmp_ln878_2_fu_364_p2;
wire   [0:0] or_ln452_2_fu_369_p2;
wire   [0:0] and_ln454_1_fu_381_p2;
wire   [0:0] or_ln452_3_fu_392_p2;
wire   [0:0] icmp_ln886_2_fu_403_p2;
wire   [0:0] and_ln454_2_fu_408_p2;
wire   [0:0] icmp_ln878_4_fu_420_p2;
wire   [0:0] or_ln452_4_fu_425_p2;
wire   [0:0] and_ln454_3_fu_437_p2;
wire   [0:0] icmp_ln878_5_fu_448_p2;
wire   [0:0] or_ln452_5_fu_453_p2;
wire   [0:0] icmp_ln886_4_fu_465_p2;
wire   [0:0] and_ln454_4_fu_470_p2;
wire   [0:0] icmp_ln878_6_fu_482_p2;
wire   [0:0] or_ln452_6_fu_487_p2;
wire   [0:0] icmp_ln886_5_fu_499_p2;
wire   [0:0] and_ln454_5_fu_504_p2;
wire   [0:0] tmp_45_fu_516_p3;
wire   [0:0] or_ln452_7_fu_523_p2;
wire   [0:0] icmp_ln886_6_fu_535_p2;
wire   [0:0] and_ln454_6_fu_540_p2;
wire   [63:0] select_ln452_6_fu_492_p3;
wire   [63:0] select_ln452_7_fu_528_p3;
wire   [63:0] select_ln452_5_fu_458_p3;
wire   [63:0] select_ln452_4_fu_430_p3;
wire   [63:0] add_ln208_1_fu_558_p2;
wire   [63:0] add_ln208_fu_552_p2;
wire   [63:0] select_ln452_3_fu_396_p3;
wire   [63:0] select_ln452_2_fu_374_p3;
wire   [63:0] select_ln452_fu_334_p3;
wire   [63:0] select_ln452_1_fu_346_p3;
wire   [63:0] add_ln208_4_fu_576_p2;
wire   [63:0] add_ln208_3_fu_570_p2;
wire   [63:0] add_ln208_5_fu_582_p2;
wire   [63:0] add_ln208_2_fu_564_p2;
wire   [63:0] select_ln454_6_fu_545_p3;
wire   [63:0] select_ln454_4_fu_475_p3;
wire   [63:0] add_ln208_7_fu_594_p2;
wire   [63:0] select_ln454_5_fu_509_p3;
wire   [63:0] select_ln454_3_fu_441_p3;
wire   [63:0] select_ln454_2_fu_413_p3;
wire   [63:0] select_ln454_1_fu_385_p3;
wire   [63:0] a_V_fu_357_p3;
wire   [63:0] add_ln208_10_fu_612_p2;
wire   [63:0] add_ln208_9_fu_606_p2;
wire   [63:0] add_ln208_11_fu_618_p2;
wire   [63:0] add_ln208_8_fu_600_p2;
wire   [211:0] tmp_s_fu_630_p9;
wire    ap_CS_fsm_state5;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 terms_read_reg_649 = 640'd0;
#0 tmp_1_reg_655 = 64'd0;
#0 tmp_2_reg_661 = 64'd0;
#0 tmp_3_reg_667 = 64'd0;
#0 tmp_4_reg_673 = 64'd0;
#0 tmp_5_reg_679 = 64'd0;
#0 tmp_6_reg_685 = 64'd0;
#0 tmp_7_reg_691 = 64'd0;
#0 trunc_ln_reg_697 = 4'd0;
#0 token_has_body_V_reg_709 = 1'd0;
#0 token_has_body_V_reg_709_pp0_iter1_reg = 1'd0;
#0 token_end_V_reg_721 = 1'd0;
#0 token_end_V_reg_721_pp0_iter1_reg = 1'd0;
#0 cmp_i_reg_726 = 1'd0;
#0 icmp_ln878_reg_738 = 1'd0;
#0 icmp_ln878_1_reg_743 = 1'd0;
#0 icmp_ln886_reg_748 = 1'd0;
#0 icmp_ln886_1_reg_753 = 1'd0;
#0 icmp_ln878_3_reg_758 = 1'd0;
#0 icmp_ln886_3_reg_763 = 1'd0;
#0 tmp_8_reg_768 = 64'd0;
#0 tmp_8_reg_768_pp0_iter1_reg = 64'd0;
#0 tmp_9_reg_773 = 4'd0;
#0 tmp_9_reg_773_pp0_iter1_reg = 4'd0;
#0 token_before_V_reg_778 = 64'd0;
#0 token_after_V_reg_783 = 64'd0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        cmp_i_reg_726 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cmp_i_reg_726 <= cmp_i_fu_225_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln878_1_reg_743 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            icmp_ln878_1_reg_743 <= icmp_ln878_1_fu_247_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln878_3_reg_758 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            icmp_ln878_3_reg_758 <= icmp_ln878_3_fu_285_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln878_reg_738 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            icmp_ln878_reg_738 <= icmp_ln878_fu_231_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln886_1_reg_753 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            icmp_ln886_1_reg_753 <= icmp_ln886_1_fu_269_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln886_3_reg_763 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            icmp_ln886_3_reg_763 <= icmp_ln886_3_fu_301_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln886_reg_748 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            icmp_ln886_reg_748 <= icmp_ln886_fu_253_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        terms_read_reg_649 <= 640'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            terms_read_reg_649 <= terms_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_1_reg_655 <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            tmp_1_reg_655 <= {{terms_dout[127:64]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_2_reg_661 <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            tmp_2_reg_661 <= {{terms_dout[191:128]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_3_reg_667 <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            tmp_3_reg_667 <= {{terms_dout[255:192]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_4_reg_673 <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            tmp_4_reg_673 <= {{terms_dout[319:256]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_5_reg_679 <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            tmp_5_reg_679 <= {{terms_dout[383:320]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_6_reg_685 <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            tmp_6_reg_685 <= {{terms_dout[447:384]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_7_reg_691 <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            tmp_7_reg_691 <= {{terms_dout[511:448]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_8_reg_768 <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            tmp_8_reg_768 <= {{terms_dout[575:512]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_8_reg_768_pp0_iter1_reg <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            tmp_8_reg_768_pp0_iter1_reg <= tmp_8_reg_768;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_9_reg_773 <= 4'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            tmp_9_reg_773 <= {{terms_dout[603:600]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_9_reg_773_pp0_iter1_reg <= 4'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            tmp_9_reg_773_pp0_iter1_reg <= tmp_9_reg_773;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        token_after_V_reg_783 <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            token_after_V_reg_783 <= token_after_V_fu_624_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        token_before_V_reg_778 <= 64'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            token_before_V_reg_778 <= token_before_V_fu_588_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        token_end_V_reg_721 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            token_end_V_reg_721 <= terms_dout[32'd592];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        token_end_V_reg_721_pp0_iter1_reg <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            token_end_V_reg_721_pp0_iter1_reg <= token_end_V_reg_721;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        token_has_body_V_reg_709 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            token_has_body_V_reg_709 <= terms_dout[32'd584];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        token_has_body_V_reg_709_pp0_iter1_reg <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            token_has_body_V_reg_709_pp0_iter1_reg <= token_has_body_V_reg_709;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        trunc_ln_reg_697 <= 4'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            trunc_ln_reg_697 <= {{terms_dout[579:576]}};
        end
    end
end

always @ (*) begin
    if (((token_end_V_fu_217_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        sums_blk_n = sums_full_n;
    end else begin
        sums_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sums_write = 1'b1;
    end else begin
        sums_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        terms_blk_n = terms_empty_n;
    end else begin
        terms_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        terms_read = 1'b1;
    end else begin
        terms_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_V_fu_357_p3 = ((and_ln454_fu_353_p2[0:0] == 1'b1) ? tmp_1_reg_655 : 64'd0);

assign add_ln208_10_fu_612_p2 = (select_ln454_1_fu_385_p3 + a_V_fu_357_p3);

assign add_ln208_11_fu_618_p2 = (add_ln208_10_fu_612_p2 + add_ln208_9_fu_606_p2);

assign add_ln208_1_fu_558_p2 = (select_ln452_5_fu_458_p3 + select_ln452_4_fu_430_p3);

assign add_ln208_2_fu_564_p2 = (add_ln208_1_fu_558_p2 + add_ln208_fu_552_p2);

assign add_ln208_3_fu_570_p2 = (select_ln452_3_fu_396_p3 + select_ln452_2_fu_374_p3);

assign add_ln208_4_fu_576_p2 = (select_ln452_fu_334_p3 + select_ln452_1_fu_346_p3);

assign add_ln208_5_fu_582_p2 = (add_ln208_4_fu_576_p2 + add_ln208_3_fu_570_p2);

assign add_ln208_7_fu_594_p2 = (select_ln454_6_fu_545_p3 + select_ln454_4_fu_475_p3);

assign add_ln208_8_fu_600_p2 = (add_ln208_7_fu_594_p2 + select_ln454_5_fu_509_p3);

assign add_ln208_9_fu_606_p2 = (select_ln454_3_fu_441_p3 + select_ln454_2_fu_413_p3);

assign add_ln208_fu_552_p2 = (select_ln452_6_fu_492_p3 + select_ln452_7_fu_528_p3);

assign and_ln454_1_fu_381_p2 = (token_has_body_V_reg_709 & icmp_ln886_1_reg_753);

assign and_ln454_2_fu_408_p2 = (token_has_body_V_reg_709 & icmp_ln886_2_fu_403_p2);

assign and_ln454_3_fu_437_p2 = (token_has_body_V_reg_709 & icmp_ln886_3_reg_763);

assign and_ln454_4_fu_470_p2 = (token_has_body_V_reg_709 & icmp_ln886_4_fu_465_p2);

assign and_ln454_5_fu_504_p2 = (token_has_body_V_reg_709 & icmp_ln886_5_fu_499_p2);

assign and_ln454_6_fu_540_p2 = (token_has_body_V_reg_709 & icmp_ln886_6_fu_535_p2);

assign and_ln454_fu_353_p2 = (token_has_body_V_reg_709 & icmp_ln886_reg_748);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (sums_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (terms_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (sums_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (terms_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (sums_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (terms_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = (terms_empty_n == 1'b0);
end

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter2 = (sums_full_n == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign cmp_i_fu_225_p2 = (token_has_body_V_fu_209_p3 ^ 1'd1);

assign icmp_ln878_1_fu_247_p2 = ((tmp_41_fu_237_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln878_2_fu_364_p2 = ((trunc_ln_reg_697 > 4'd2) ? 1'b1 : 1'b0);

assign icmp_ln878_3_fu_285_p2 = ((tmp_43_fu_275_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln878_4_fu_420_p2 = ((trunc_ln_reg_697 > 4'd4) ? 1'b1 : 1'b0);

assign icmp_ln878_5_fu_448_p2 = ((trunc_ln_reg_697 > 4'd5) ? 1'b1 : 1'b0);

assign icmp_ln878_6_fu_482_p2 = ((trunc_ln_reg_697 > 4'd6) ? 1'b1 : 1'b0);

assign icmp_ln878_fu_231_p2 = ((trunc_ln_fu_199_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln886_1_fu_269_p2 = ((tmp_42_fu_259_p4 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln886_2_fu_403_p2 = ((trunc_ln_reg_697 < 4'd3) ? 1'b1 : 1'b0);

assign icmp_ln886_3_fu_301_p2 = ((tmp_44_fu_291_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln886_4_fu_465_p2 = ((trunc_ln_reg_697 < 4'd5) ? 1'b1 : 1'b0);

assign icmp_ln886_5_fu_499_p2 = ((trunc_ln_reg_697 < 4'd6) ? 1'b1 : 1'b0);

assign icmp_ln886_6_fu_535_p2 = ((trunc_ln_reg_697 < 4'd7) ? 1'b1 : 1'b0);

assign icmp_ln886_fu_253_p2 = ((trunc_ln_fu_199_p4 == 4'd0) ? 1'b1 : 1'b0);

assign or_ln452_1_fu_342_p2 = (icmp_ln878_1_reg_743 | cmp_i_reg_726);

assign or_ln452_2_fu_369_p2 = (icmp_ln878_2_fu_364_p2 | cmp_i_reg_726);

assign or_ln452_3_fu_392_p2 = (icmp_ln878_3_reg_758 | cmp_i_reg_726);

assign or_ln452_4_fu_425_p2 = (icmp_ln878_4_fu_420_p2 | cmp_i_reg_726);

assign or_ln452_5_fu_453_p2 = (icmp_ln878_5_fu_448_p2 | cmp_i_reg_726);

assign or_ln452_6_fu_487_p2 = (icmp_ln878_6_fu_482_p2 | cmp_i_reg_726);

assign or_ln452_7_fu_523_p2 = (tmp_45_fu_516_p3 | cmp_i_reg_726);

assign or_ln452_fu_330_p2 = (icmp_ln878_reg_738 | cmp_i_reg_726);

assign select_ln452_1_fu_346_p3 = ((or_ln452_1_fu_342_p2[0:0] == 1'b1) ? tmp_1_reg_655 : 64'd0);

assign select_ln452_2_fu_374_p3 = ((or_ln452_2_fu_369_p2[0:0] == 1'b1) ? tmp_2_reg_661 : 64'd0);

assign select_ln452_3_fu_396_p3 = ((or_ln452_3_fu_392_p2[0:0] == 1'b1) ? tmp_3_reg_667 : 64'd0);

assign select_ln452_4_fu_430_p3 = ((or_ln452_4_fu_425_p2[0:0] == 1'b1) ? tmp_4_reg_673 : 64'd0);

assign select_ln452_5_fu_458_p3 = ((or_ln452_5_fu_453_p2[0:0] == 1'b1) ? tmp_5_reg_679 : 64'd0);

assign select_ln452_6_fu_492_p3 = ((or_ln452_6_fu_487_p2[0:0] == 1'b1) ? tmp_6_reg_685 : 64'd0);

assign select_ln452_7_fu_528_p3 = ((or_ln452_7_fu_523_p2[0:0] == 1'b1) ? tmp_7_reg_691 : 64'd0);

assign select_ln452_fu_334_p3 = ((or_ln452_fu_330_p2[0:0] == 1'b1) ? tmp_fu_327_p1 : 64'd0);

assign select_ln454_1_fu_385_p3 = ((and_ln454_1_fu_381_p2[0:0] == 1'b1) ? tmp_2_reg_661 : 64'd0);

assign select_ln454_2_fu_413_p3 = ((and_ln454_2_fu_408_p2[0:0] == 1'b1) ? tmp_3_reg_667 : 64'd0);

assign select_ln454_3_fu_441_p3 = ((and_ln454_3_fu_437_p2[0:0] == 1'b1) ? tmp_4_reg_673 : 64'd0);

assign select_ln454_4_fu_475_p3 = ((and_ln454_4_fu_470_p2[0:0] == 1'b1) ? tmp_5_reg_679 : 64'd0);

assign select_ln454_5_fu_509_p3 = ((and_ln454_5_fu_504_p2[0:0] == 1'b1) ? tmp_6_reg_685 : 64'd0);

assign select_ln454_6_fu_545_p3 = ((and_ln454_6_fu_540_p2[0:0] == 1'b1) ? tmp_7_reg_691 : 64'd0);

assign start_out = real_start;

assign sums_din = tmp_s_fu_630_p9;

assign tmp_41_fu_237_p4 = {{terms_dout[579:577]}};

assign tmp_42_fu_259_p4 = {{terms_dout[579:577]}};

assign tmp_43_fu_275_p4 = {{terms_dout[579:578]}};

assign tmp_44_fu_291_p4 = {{terms_dout[579:578]}};

assign tmp_45_fu_516_p3 = terms_read_reg_649[32'd579];

assign tmp_fu_327_p1 = terms_read_reg_649[63:0];

assign tmp_s_fu_630_p9 = {{{{{{{{tmp_9_reg_773_pp0_iter1_reg}, {7'd0}}, {token_end_V_reg_721_pp0_iter1_reg}}, {7'd0}}, {token_has_body_V_reg_709_pp0_iter1_reg}}, {tmp_8_reg_768_pp0_iter1_reg}}, {token_after_V_reg_783}}, {token_before_V_reg_778}};

assign token_after_V_fu_624_p2 = (add_ln208_11_fu_618_p2 + add_ln208_8_fu_600_p2);

assign token_before_V_fu_588_p2 = (add_ln208_5_fu_582_p2 + add_ln208_2_fu_564_p2);

assign token_end_V_fu_217_p3 = terms_dout[32'd592];

assign token_has_body_V_fu_209_p3 = terms_dout[32'd584];

assign trunc_ln_fu_199_p4 = {{terms_dout[579:576]}};

endmodule //lwe_decrypt_reduce_mask_beats
