// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module lwe_decrypt_frame_input_beats (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        beats_dout,
        beats_empty_n,
        beats_read,
        frames_din,
        frames_full_n,
        frames_write,
        input_count_dout,
        input_count_empty_n,
        input_count_read,
        layout_dout,
        layout_empty_n,
        layout_read,
        layout_out_din,
        layout_out_full_n,
        layout_out_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state6 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [1023:0] beats_dout;
input   beats_empty_n;
output   beats_read;
output  [1535:0] frames_din;
input   frames_full_n;
output   frames_write;
input  [31:0] input_count_dout;
input   input_count_empty_n;
output   input_count_read;
input  [1:0] layout_dout;
input   layout_empty_n;
output   layout_read;
output  [1:0] layout_out_din;
input   layout_out_full_n;
output   layout_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg beats_read;
reg frames_write;
reg input_count_read;
reg layout_read;
reg layout_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    beats_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg   [0:0] ap_phi_mux_phi_ln257_phi_fu_129_p4;
reg    frames_blk_n;
reg    ap_enable_reg_pp0_iter3;
reg   [0:0] phi_ln257_reg_125;
reg   [0:0] phi_ln257_reg_125_pp0_iter2_reg;
reg    input_count_blk_n;
reg    layout_blk_n;
reg    layout_out_blk_n;
reg   [0:0] phi_ln257_reg_125_pp0_iter1_reg;
reg    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_state5_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_11001;
reg   [11:0] position_V_3_reg_137;
reg   [11:0] position_V_3_reg_137_pp0_iter2_reg;
reg   [31:0] processed_V_5_reg_149;
reg   [1:0] radix_index_V_reg_160;
reg   [31:0] input_count_read_reg_464;
wire   [11:0] span_V_fu_197_p3;
reg   [11:0] span_V_reg_470;
wire   [0:0] lnot_i_i115_i_fu_205_p2;
reg   [0:0] lnot_i_i115_i_reg_476;
wire   [32:0] input_count_cast_i_fu_211_p1;
reg   [32:0] input_count_cast_i_reg_483;
wire   [12:0] zext_ln174_fu_215_p1;
reg   [12:0] zext_ln174_reg_488;
reg   [1023:0] token_beat_reg_493;
reg   [1023:0] token_beat_reg_493_pp0_iter1_reg;
reg   [1023:0] token_beat_reg_493_pp0_iter2_reg;
wire   [0:0] finished_fu_219_p3;
reg   [0:0] finished_reg_498;
reg   [0:0] finished_reg_498_pp0_iter1_reg;
reg   [3:0] tmp_s_reg_505;
wire   [0:0] xor_ln145_fu_237_p2;
reg   [0:0] xor_ln145_reg_511;
wire   [0:0] token_complete_V_fu_264_p2;
reg   [0:0] token_complete_V_reg_517;
reg   [0:0] token_complete_V_reg_517_pp0_iter2_reg;
wire   [0:0] and_ln882_fu_281_p2;
reg   [0:0] and_ln882_reg_522;
wire   [11:0] position_V_2_fu_294_p3;
reg   [11:0] position_V_2_reg_528;
reg    ap_enable_reg_pp0_iter1;
wire   [0:0] token_past_count_V_fu_312_p2;
reg   [0:0] token_past_count_V_reg_533;
wire   [0:0] token_last_item_V_fu_343_p2;
reg   [0:0] token_last_item_V_reg_538;
wire   [31:0] processed_V_4_fu_411_p3;
reg    ap_enable_reg_pp0_iter2;
wire   [1:0] radix_index_V_3_fu_425_p3;
wire   [0:0] empty_fu_432_p3;
reg   [0:0] empty_reg_553;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_flush_enable;
reg    ap_condition_pp0_exit_iter2_state4;
reg   [11:0] ap_phi_mux_position_V_3_phi_fu_141_p4;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln870_fu_171_p2;
wire   [0:0] icmp_ln870_2_fu_177_p2;
wire   [0:0] or_ln301_fu_191_p2;
wire   [11:0] select_ln301_fu_183_p3;
wire   [12:0] zext_ln208_1_fu_247_p1;
wire   [12:0] zext_ln208_fu_243_p1;
wire   [12:0] total_fu_253_p2;
wire   [0:0] icmp_ln882_1_fu_259_p2;
wire   [11:0] zext_ln208_2_fu_250_p1;
wire   [11:0] position_V_fu_270_p2;
wire   [11:0] sub_ln213_fu_276_p2;
wire   [11:0] select_ln882_fu_286_p3;
wire   [0:0] icmp_ln882_fu_301_p2;
wire   [0:0] xor_ln882_fu_306_p2;
wire   [32:0] zext_ln1346_fu_317_p1;
wire   [32:0] ret_fu_321_p2;
wire   [0:0] icmp_ln870_4_fu_332_p2;
wire   [0:0] tmp_fu_338_p2;
wire   [0:0] icmp_ln870_3_fu_327_p2;
wire   [0:0] icmp_ln874_34_fu_354_p2;
wire   [0:0] icmp_ln271_fu_360_p2;
wire   [0:0] xor_ln752_fu_372_p2;
wire   [0:0] and_ln275_fu_378_p2;
wire   [31:0] processed_V_fu_384_p2;
wire   [31:0] processed_V_2_fu_390_p3;
wire   [31:0] processed_V_3_fu_404_p3;
wire   [1:0] radix_index_V_1_fu_398_p2;
wire   [1:0] radix_index_V_2_fu_418_p3;
wire   [0:0] icmp_ln874_fu_349_p2;
wire   [0:0] or_ln271_fu_366_p2;
wire    ap_CS_fsm_state6;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 phi_ln257_reg_125 = 1'd0;
#0 phi_ln257_reg_125_pp0_iter2_reg = 1'd0;
#0 phi_ln257_reg_125_pp0_iter1_reg = 1'd0;
#0 position_V_3_reg_137 = 12'd0;
#0 position_V_3_reg_137_pp0_iter2_reg = 12'd0;
#0 processed_V_5_reg_149 = 32'd0;
#0 radix_index_V_reg_160 = 2'd0;
#0 input_count_read_reg_464 = 32'd0;
#0 span_V_reg_470 = 12'd0;
#0 lnot_i_i115_i_reg_476 = 1'd0;
#0 input_count_cast_i_reg_483 = 33'd0;
#0 zext_ln174_reg_488 = 13'd0;
#0 token_beat_reg_493 = 1024'd0;
#0 token_beat_reg_493_pp0_iter1_reg = 1024'd0;
#0 token_beat_reg_493_pp0_iter2_reg = 1024'd0;
#0 finished_reg_498 = 1'd0;
#0 finished_reg_498_pp0_iter1_reg = 1'd0;
#0 tmp_s_reg_505 = 4'd0;
#0 xor_ln145_reg_511 = 1'd0;
#0 token_complete_V_reg_517 = 1'd0;
#0 token_complete_V_reg_517_pp0_iter2_reg = 1'd0;
#0 and_ln882_reg_522 = 1'd0;
#0 position_V_2_reg_528 = 12'd0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 token_past_count_V_reg_533 = 1'd0;
#0 token_last_item_V_reg_538 = 1'd0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 empty_reg_553 = 1'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        and_ln882_reg_522 <= 1'd0;
    end else begin
        if (((phi_ln257_reg_125 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            and_ln882_reg_522 <= and_ln882_fu_281_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((real_start == 1'b0) | (layout_out_full_n == 1'b0) | (layout_empty_n == 1'b0) | (input_count_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter2_state4) & (ap_enable_reg_pp0_iter1 == 1'b0)) | (~((real_start == 1'b0) | (layout_out_full_n == 1'b0) | (layout_empty_n == 1'b0) | (input_count_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter2_state4))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter1;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if ((~((real_start == 1'b0) | (layout_out_full_n == 1'b0) | (layout_empty_n == 1'b0) | (input_count_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        empty_reg_553 <= 1'd0;
    end else begin
        if (((phi_ln257_reg_125_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            empty_reg_553 <= empty_fu_432_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        finished_reg_498 <= 1'd0;
    end else begin
        if (((ap_phi_mux_phi_ln257_phi_fu_129_p4 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            finished_reg_498 <= beats_dout[32'd600];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        finished_reg_498_pp0_iter1_reg <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            finished_reg_498_pp0_iter1_reg <= finished_reg_498;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                input_count_cast_i_reg_483[0] <= 1'b0;
        input_count_cast_i_reg_483[1] <= 1'b0;
        input_count_cast_i_reg_483[2] <= 1'b0;
        input_count_cast_i_reg_483[3] <= 1'b0;
        input_count_cast_i_reg_483[4] <= 1'b0;
        input_count_cast_i_reg_483[5] <= 1'b0;
        input_count_cast_i_reg_483[6] <= 1'b0;
        input_count_cast_i_reg_483[7] <= 1'b0;
        input_count_cast_i_reg_483[8] <= 1'b0;
        input_count_cast_i_reg_483[9] <= 1'b0;
        input_count_cast_i_reg_483[10] <= 1'b0;
        input_count_cast_i_reg_483[11] <= 1'b0;
        input_count_cast_i_reg_483[12] <= 1'b0;
        input_count_cast_i_reg_483[13] <= 1'b0;
        input_count_cast_i_reg_483[14] <= 1'b0;
        input_count_cast_i_reg_483[15] <= 1'b0;
        input_count_cast_i_reg_483[16] <= 1'b0;
        input_count_cast_i_reg_483[17] <= 1'b0;
        input_count_cast_i_reg_483[18] <= 1'b0;
        input_count_cast_i_reg_483[19] <= 1'b0;
        input_count_cast_i_reg_483[20] <= 1'b0;
        input_count_cast_i_reg_483[21] <= 1'b0;
        input_count_cast_i_reg_483[22] <= 1'b0;
        input_count_cast_i_reg_483[23] <= 1'b0;
        input_count_cast_i_reg_483[24] <= 1'b0;
        input_count_cast_i_reg_483[25] <= 1'b0;
        input_count_cast_i_reg_483[26] <= 1'b0;
        input_count_cast_i_reg_483[27] <= 1'b0;
        input_count_cast_i_reg_483[28] <= 1'b0;
        input_count_cast_i_reg_483[29] <= 1'b0;
        input_count_cast_i_reg_483[30] <= 1'b0;
        input_count_cast_i_reg_483[31] <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
                        input_count_cast_i_reg_483[31 : 0] <= input_count_cast_i_fu_211_p1[31 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        input_count_read_reg_464 <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            input_count_read_reg_464 <= input_count_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        lnot_i_i115_i_reg_476 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            lnot_i_i115_i_reg_476 <= lnot_i_i115_i_fu_205_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        phi_ln257_reg_125 <= 1'd0;
    end else begin
        if (((phi_ln257_reg_125 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            phi_ln257_reg_125 <= xor_ln145_reg_511;
        end else if ((~((real_start == 1'b0) | (layout_out_full_n == 1'b0) | (layout_empty_n == 1'b0) | (input_count_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            phi_ln257_reg_125 <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        phi_ln257_reg_125_pp0_iter1_reg <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            phi_ln257_reg_125_pp0_iter1_reg <= phi_ln257_reg_125;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        phi_ln257_reg_125_pp0_iter2_reg <= 1'd0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_11001)) begin
            phi_ln257_reg_125_pp0_iter2_reg <= phi_ln257_reg_125_pp0_iter1_reg;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        position_V_2_reg_528 <= 12'd0;
    end else begin
        if (((phi_ln257_reg_125 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            position_V_2_reg_528 <= position_V_2_fu_294_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        position_V_3_reg_137 <= 12'd0;
    end else begin
        if (((phi_ln257_reg_125_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            position_V_3_reg_137 <= position_V_2_reg_528;
        end else if ((~((real_start == 1'b0) | (layout_out_full_n == 1'b0) | (layout_empty_n == 1'b0) | (input_count_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            position_V_3_reg_137 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        position_V_3_reg_137_pp0_iter2_reg <= 12'd0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_11001)) begin
            position_V_3_reg_137_pp0_iter2_reg <= position_V_3_reg_137;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        processed_V_5_reg_149 <= 32'd0;
    end else begin
        if (((phi_ln257_reg_125_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            processed_V_5_reg_149 <= processed_V_4_fu_411_p3;
        end else if ((~((real_start == 1'b0) | (layout_out_full_n == 1'b0) | (layout_empty_n == 1'b0) | (input_count_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            processed_V_5_reg_149 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        radix_index_V_reg_160 <= 2'd0;
    end else begin
        if (((phi_ln257_reg_125_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            radix_index_V_reg_160 <= radix_index_V_3_fu_425_p3;
        end else if ((~((real_start == 1'b0) | (layout_out_full_n == 1'b0) | (layout_empty_n == 1'b0) | (input_count_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            radix_index_V_reg_160 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                span_V_reg_470[0] <= 1'b0;
        span_V_reg_470[3] <= 1'b0;
        span_V_reg_470[10] <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
                        span_V_reg_470[0] <= span_V_fu_197_p3[0];
            span_V_reg_470[3] <= span_V_fu_197_p3[3];
            span_V_reg_470[10] <= span_V_fu_197_p3[10];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_s_reg_505 <= 4'd0;
    end else begin
        if (((ap_phi_mux_phi_ln257_phi_fu_129_p4 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            tmp_s_reg_505 <= {{beats_dout[587:584]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        token_beat_reg_493 <= 1024'd0;
    end else begin
        if (((ap_phi_mux_phi_ln257_phi_fu_129_p4 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            token_beat_reg_493 <= beats_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        token_beat_reg_493_pp0_iter1_reg <= 1024'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            token_beat_reg_493_pp0_iter1_reg <= token_beat_reg_493;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        token_beat_reg_493_pp0_iter2_reg <= 1024'd0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_11001)) begin
            token_beat_reg_493_pp0_iter2_reg <= token_beat_reg_493_pp0_iter1_reg;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        token_complete_V_reg_517 <= 1'd0;
    end else begin
        if (((phi_ln257_reg_125 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            token_complete_V_reg_517 <= token_complete_V_fu_264_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        token_complete_V_reg_517_pp0_iter2_reg <= 1'd0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_11001)) begin
            token_complete_V_reg_517_pp0_iter2_reg <= token_complete_V_reg_517;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        token_last_item_V_reg_538 <= 1'd0;
    end else begin
        if (((phi_ln257_reg_125_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            token_last_item_V_reg_538 <= token_last_item_V_fu_343_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        token_past_count_V_reg_533 <= 1'd0;
    end else begin
        if (((phi_ln257_reg_125_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            token_past_count_V_reg_533 <= token_past_count_V_fu_312_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        xor_ln145_reg_511 <= 1'd0;
    end else begin
        if (((ap_phi_mux_phi_ln257_phi_fu_129_p4 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            xor_ln145_reg_511 <= xor_ln145_fu_237_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                zext_ln174_reg_488[0] <= 1'b0;
        zext_ln174_reg_488[3] <= 1'b0;
        zext_ln174_reg_488[10] <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
                        zext_ln174_reg_488[0] <= zext_ln174_fu_215_p1[0];
            zext_ln174_reg_488[3] <= zext_ln174_fu_215_p1[3];
            zext_ln174_reg_488[10] <= zext_ln174_fu_215_p1[10];
        end
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_condition_pp0_exit_iter2_state4 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter2_state4 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_phi_mux_phi_ln257_phi_fu_129_p4 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((phi_ln257_reg_125 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_phi_mux_phi_ln257_phi_fu_129_p4 = xor_ln145_reg_511;
    end else begin
        ap_phi_mux_phi_ln257_phi_fu_129_p4 = phi_ln257_reg_125;
    end
end

always @ (*) begin
    if (((phi_ln257_reg_125_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_position_V_3_phi_fu_141_p4 = position_V_2_reg_528;
    end else begin
        ap_phi_mux_position_V_3_phi_fu_141_p4 = position_V_3_reg_137;
    end
end

always @ (*) begin
    if (((ap_phi_mux_phi_ln257_phi_fu_129_p4 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        beats_blk_n = beats_empty_n;
    end else begin
        beats_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_phi_mux_phi_ln257_phi_fu_129_p4 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        beats_read = 1'b1;
    end else begin
        beats_read = 1'b0;
    end
end

always @ (*) begin
    if (((phi_ln257_reg_125_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        frames_blk_n = frames_full_n;
    end else begin
        frames_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((phi_ln257_reg_125_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        frames_write = 1'b1;
    end else begin
        frames_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        input_count_blk_n = input_count_empty_n;
    end else begin
        input_count_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (layout_out_full_n == 1'b0) | (layout_empty_n == 1'b0) | (input_count_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        input_count_read = 1'b1;
    end else begin
        input_count_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layout_blk_n = layout_empty_n;
    end else begin
        layout_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layout_out_blk_n = layout_out_full_n;
    end else begin
        layout_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (layout_out_full_n == 1'b0) | (layout_empty_n == 1'b0) | (input_count_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layout_out_write = 1'b1;
    end else begin
        layout_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (layout_out_full_n == 1'b0) | (layout_empty_n == 1'b0) | (input_count_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layout_read = 1'b1;
    end else begin
        layout_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (layout_out_full_n == 1'b0) | (layout_empty_n == 1'b0) | (input_count_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln275_fu_378_p2 = (xor_ln752_fu_372_p2 & icmp_ln870_4_fu_332_p2);

assign and_ln882_fu_281_p2 = (xor_ln145_reg_511 & token_complete_V_fu_264_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((phi_ln257_reg_125_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (frames_full_n == 1'b0)) | ((ap_phi_mux_phi_ln257_phi_fu_129_p4 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (beats_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((phi_ln257_reg_125_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (frames_full_n == 1'b0)) | ((ap_phi_mux_phi_ln257_phi_fu_129_p4 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (beats_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((phi_ln257_reg_125_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (frames_full_n == 1'b0)) | ((ap_phi_mux_phi_ln257_phi_fu_129_p4 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (beats_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (layout_out_full_n == 1'b0) | (layout_empty_n == 1'b0) | (input_count_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = ((ap_phi_mux_phi_ln257_phi_fu_129_p4 == 1'd1) & (beats_empty_n == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp0_stage0_iter3 = ((phi_ln257_reg_125_pp0_iter2_reg == 1'd1) & (frames_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign empty_fu_432_p3 = ((lnot_i_i115_i_reg_476[0:0] == 1'b1) ? icmp_ln874_fu_349_p2 : or_ln271_fu_366_p2);

assign finished_fu_219_p3 = beats_dout[32'd600];

assign frames_din = {{{{{{{{{{{{{{{{{{{{{{{{455'd0}, {empty_reg_553}}}, {7'd0}}}, {token_last_item_V_reg_538}}}, {7'd0}}}, {token_past_count_V_reg_533}}}, {7'd0}}}, {token_complete_V_reg_517_pp0_iter2_reg}}}, {4'd0}}}, {span_V_reg_470}}}, {4'd0}}}, {position_V_3_reg_137_pp0_iter2_reg}}}, {token_beat_reg_493_pp0_iter2_reg}};

assign icmp_ln271_fu_360_p2 = ((position_V_3_reg_137 != 12'd0) ? 1'b1 : 1'b0);

assign icmp_ln870_2_fu_177_p2 = ((layout_dout == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln870_3_fu_327_p2 = ((ret_fu_321_p2 == input_count_cast_i_reg_483) ? 1'b1 : 1'b0);

assign icmp_ln870_4_fu_332_p2 = ((radix_index_V_reg_160 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln870_fu_171_p2 = ((layout_dout == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln874_34_fu_354_p2 = ((radix_index_V_reg_160 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln874_fu_349_p2 = ((processed_V_5_reg_149 != input_count_read_reg_464) ? 1'b1 : 1'b0);

assign icmp_ln882_1_fu_259_p2 = ((total_fu_253_p2 < zext_ln174_reg_488) ? 1'b1 : 1'b0);

assign icmp_ln882_fu_301_p2 = ((processed_V_5_reg_149 < input_count_read_reg_464) ? 1'b1 : 1'b0);

assign input_count_cast_i_fu_211_p1 = input_count_dout;

assign layout_out_din = layout_dout;

assign lnot_i_i115_i_fu_205_p2 = ((input_count_dout != 32'd0) ? 1'b1 : 1'b0);

assign or_ln271_fu_366_p2 = (icmp_ln874_34_fu_354_p2 | icmp_ln271_fu_360_p2);

assign or_ln301_fu_191_p2 = (icmp_ln870_fu_171_p2 | icmp_ln870_2_fu_177_p2);

assign position_V_2_fu_294_p3 = ((finished_reg_498[0:0] == 1'b1) ? ap_phi_mux_position_V_3_phi_fu_141_p4 : select_ln882_fu_286_p3);

assign position_V_fu_270_p2 = (zext_ln208_2_fu_250_p1 + ap_phi_mux_position_V_3_phi_fu_141_p4);

assign processed_V_2_fu_390_p3 = ((and_ln275_fu_378_p2[0:0] == 1'b1) ? processed_V_fu_384_p2 : processed_V_5_reg_149);

assign processed_V_3_fu_404_p3 = ((and_ln882_reg_522[0:0] == 1'b1) ? processed_V_2_fu_390_p3 : processed_V_5_reg_149);

assign processed_V_4_fu_411_p3 = ((finished_reg_498_pp0_iter1_reg[0:0] == 1'b1) ? processed_V_5_reg_149 : processed_V_3_fu_404_p3);

assign processed_V_fu_384_p2 = (processed_V_5_reg_149 + 32'd1);

assign radix_index_V_1_fu_398_p2 = (radix_index_V_reg_160 + 2'd1);

assign radix_index_V_2_fu_418_p3 = ((and_ln882_reg_522[0:0] == 1'b1) ? radix_index_V_1_fu_398_p2 : radix_index_V_reg_160);

assign radix_index_V_3_fu_425_p3 = ((finished_reg_498_pp0_iter1_reg[0:0] == 1'b1) ? radix_index_V_reg_160 : radix_index_V_2_fu_418_p3);

assign ret_fu_321_p2 = (zext_ln1346_fu_317_p1 + 33'd1);

assign select_ln301_fu_183_p3 = ((icmp_ln870_fu_171_p2[0:0] == 1'b1) ? 12'd3072 : 12'd2056);

assign select_ln882_fu_286_p3 = ((and_ln882_fu_281_p2[0:0] == 1'b1) ? sub_ln213_fu_276_p2 : position_V_fu_270_p2);

assign span_V_fu_197_p3 = ((or_ln301_fu_191_p2[0:0] == 1'b1) ? select_ln301_fu_183_p3 : 12'd2049);

assign start_out = real_start;

assign sub_ln213_fu_276_p2 = (position_V_fu_270_p2 - span_V_reg_470);

assign tmp_fu_338_p2 = (lnot_i_i115_i_reg_476 & icmp_ln870_4_fu_332_p2);

assign token_complete_V_fu_264_p2 = (icmp_ln882_1_fu_259_p2 ^ 1'd1);

assign token_last_item_V_fu_343_p2 = (tmp_fu_338_p2 & icmp_ln870_3_fu_327_p2);

assign token_past_count_V_fu_312_p2 = (xor_ln882_fu_306_p2 & lnot_i_i115_i_reg_476);

assign total_fu_253_p2 = (zext_ln208_1_fu_247_p1 + zext_ln208_fu_243_p1);

assign xor_ln145_fu_237_p2 = (finished_fu_219_p3 ^ 1'd1);

assign xor_ln752_fu_372_p2 = (token_past_count_V_fu_312_p2 ^ 1'd1);

assign xor_ln882_fu_306_p2 = (icmp_ln882_fu_301_p2 ^ 1'd1);

assign zext_ln1346_fu_317_p1 = processed_V_5_reg_149;

assign zext_ln174_fu_215_p1 = span_V_fu_197_p3;

assign zext_ln208_1_fu_247_p1 = tmp_s_reg_505;

assign zext_ln208_2_fu_250_p1 = tmp_s_reg_505;

assign zext_ln208_fu_243_p1 = ap_phi_mux_position_V_3_phi_fu_141_p4;

always @ (posedge ap_clk) begin
    span_V_reg_470[2:1] <= 2'b00;
    span_V_reg_470[9:4] <= 6'b000000;
    span_V_reg_470[11] <= 1'b1;
    input_count_cast_i_reg_483[32] <= 1'b0;
    zext_ln174_reg_488[2:1] <= 2'b00;
    zext_ln174_reg_488[9:4] <= 6'b000000;
    zext_ln174_reg_488[12:11] <= 2'b01;
end

endmodule //lwe_decrypt_frame_input_beats
